In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

In [3]:
full_catcher_df = pd.read_sql("SELECT * FROM jobma_catcher", con=engine)
catcher_df = pd.read_sql("SELECT * FROM jobma_catcher where jobma_catcher_parent=0", con=engine)
login_df=pd.read_sql("Select * FROM jobma_login", engine)
wallet_df = pd.read_sql("Select * FROM wallet", engine) 
subscription_df = pd.read_sql("Select * FROM subscription_history", engine)

# #kits created
## ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine)
pre_recorded_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine)

# #job posted and invitation and pitchers
job_posting_df = pd.read_sql("SELECT * FROM jobma_employer_job_posting", engine)
invitation_df = pd.read_sql("Select * FROM jobma_pitcher_invitations", engine)
pitchers_df = pd.read_sql("SELECT * FROM jobma_pitcher_applied_jobs", engine) 

# #candidate interview response data, #just for pre-recorded type, # live interview type
##
pre_rec_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews", engine) 
live_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews_online", engine)
# ai_interviews_df = pd.read_sql("SELECT * FROM jobma_ai_interviews", engine)

In [4]:
catcher_df.shape

(4466, 69)

In [5]:
catcher_df =catcher_df[['jobma_catcher_id',
                        # 'jobma_catcher_otype',#Null values mostly
                        'approval',
                        'subscription_status',
                        # 'jobma_catcher_is_deleted',#null values
                        'jobma_catcher_title',
                        'jobma_catcher_email',#for joining with login
                        # 'jobma_catcher_sub_accounts',#empty values
                        'jobma_catcher_status',
                        'jobma_catcher_creation',
                        'jobma_catcher_type',
                        'is_premium',
                        # 'jobma_verified',#only 1 vlues
                        'sub_user',
                        'per_sub_user',
                        'currency',
                        'company_size',]].copy()

In [6]:
catcher_df.shape

(4466, 13)

In [7]:
# Calculating days
catcher_df['jobma_catcher_creation'] = pd.to_datetime(catcher_df['jobma_catcher_creation'], errors='coerce')
catcher_df['days_since_creation'] = (pd.Timestamp('today') - catcher_df['jobma_catcher_creation']).dt.days

In [8]:
catcher_df['jobma_catcher_status'] = catcher_df['jobma_catcher_status'].replace('-1', 0).astype(int)
catcher_df['subscription_status'] = catcher_df['subscription_status'].replace('0', 1).astype(int)
# catcher_df['jobma_verified'] = catcher_df['jobma_verified'].astype(int)

In [9]:
catcher_df['is_premium'] = catcher_df['is_premium'].replace('', 0).astype(int)
catcher_df['currency'] = catcher_df['currency'].replace('', 0).astype(int)

In [10]:
catcher_df['jobma_catcher_type'] = catcher_df['jobma_catcher_type'].fillna(0).astype(int)

In [11]:
catcher_df.drop('jobma_catcher_creation', axis=1, inplace=True)

In [12]:
catcher_df['company_size'] = catcher_df['company_size'].fillna(catcher_df['company_size'].mode()[0])

# Login_df

In [13]:
new_login_df=login_df.copy()

In [14]:
# merged_df = pd.merge(
#     catcher_df,
#     new_login_df,
#     how='left',
#     left_on='jobma_catcher_id',
#     right_on='jobma_user_id'
# )


# merged_df2 = pd.merge(
#     catcher_df,
#     new_login_df,
#     how='left',
#     left_on='jobma_catcher_id',
#     right_on='jobma_login_id'
# )

In [15]:
login_df=login_df[['jobma_user_name','jobma_login_status', 'jobma_last_login', 'created_at']]

In [16]:
login_df[['jobma_last_login', 'created_at']] = login_df[['jobma_last_login', 'created_at']].apply(pd.to_datetime, errors='coerce')
login_df['days_since_login'] = (pd.Timestamp('today') - login_df['jobma_last_login']).dt.days
login_df['days_since_creation'] = (pd.Timestamp('today') - login_df['created_at']).dt.days

C:\Users\SSI\AppData\Local\Temp\ipykernel_10520\976731209.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  login_df[['jobma_last_login', 'created_at']] = login_df[['jobma_last_login', 'created_at']].apply(pd.to_datetime, errors='coerce')

In [17]:
login_df

,jobma_user_name,jobma_login_status,jobma_last_login,created_at,days_since_login,days_since_creation
0,amit.chaudhary2022@gmail.com,1,2023-10-16 07:49:26,NaT,555.0,NaN
1,superadmin@mailinator.com,1,2023-05-29 07:33:47,NaT,695.0,NaN
2,gaurava@selectsourceintl.com,1,NaT,2016-11-23 20:53:27,NaN,3072.0
3,SMandeep@selectsourceintl.com,1,NaT,NaT,NaN,NaN
4,jobma1001@yopmail.com,1,2024-04-18 11:14:39,NaT,370.0,NaN
...,...,...,...,...,...,...
10177,Surpreet52542@yopmail.com,0,NaT,2024-06-10 17:12:55,NaN,317.0
10178,Pratik43@yopmail.com,0,NaT,2024-06-10 17:17:05,NaN,317.0
10179,SubuserCred32@yopmail.com,0,NaT,2024-06-10 17:24:17,NaN,317.0
10180,MainUser2562@yopmail.com,0,NaT,2024-06-10 17:30:00,NaN,317.0
10181,ChampakPatil@yopmail.com,0,NaT,2024-06-10 18:08:06,NaN,316.0

In [18]:
login_df['jobma_login_status'].unique()

array(['1', None, '0', ''], dtype=object)

In [19]:
login_df['jobma_login_status'] = login_df['jobma_login_status'].replace(['', None], 0).astype(int)

In [20]:
login_df = login_df.groupby('jobma_user_name').agg(number_of_logins=('jobma_user_name', 'count'),
                                                   jobma_login_status=('jobma_login_status', 'max'),
                                                   days_since_login=('days_since_login', 'max'),
                                                   days_since_creation=('days_since_creation', 'max')
                                                  ).reset_index()

In [21]:
login_df

,jobma_user_name,number_of_logins,jobma_login_status,days_since_login,days_since_creation
0,,468,1,428.0,2751.0
1,0010sub@yopmail.com,1,0,NaN,938.0
2,0011sub@yopmail.com,1,0,NaN,938.0
3,0012sub@yopmail.com,1,0,NaN,937.0
4,0013sub@yopmail.com,1,0,NaN,937.0
...,...,...,...,...,...
9663,zubir@yopmail.com,1,0,1064.0,1064.0
9664,zxc@yopmail.com,1,0,NaN,1064.0
9665,zxcv@yopmail.com,1,0,1667.0,1667.0
9666,zxcvb@yopmail.com,1,0,1064.0,1064.0
9667,zxcvzdhjcvdskjcvzcf@yopmail.com,1,0,1671.0,1672.0

In [22]:
login_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   jobma_user_name      9668 non-null   object
 1   number_of_logins     9668 non-null   int64
 2   jobma_login_status   9668 non-null   int64
 3   days_since_login     6070 non-null   float64
 4   days_since_creation  9641 non-null   float64
dtypes: float64(2), int64(2), object(1)
memory usage: 377.8+ KB

In [23]:
login_df.nunique()

jobma_user_name        9668
number_of_logins          6
jobma_login_status        2
days_since_login        870
days_since_creation    1149
dtype: int64

In [24]:
login_df['days_since_login'] = login_df['days_since_login'].fillna(login_df['days_since_creation']).fillna(1)

In [25]:
login_df.drop('days_since_creation', axis=1, inplace=True)

In [26]:
login_df.rename(columns={'jobma_user_name': 'jobma_catcher_email'}, inplace=True)

In [65]:
login_df

,jobma_catcher_email,number_of_logins,jobma_login_status,days_since_login
0,,468,1,428.0
1,0010sub@yopmail.com,1,0,938.0
2,0011sub@yopmail.com,1,0,938.0
3,0012sub@yopmail.com,1,0,937.0
4,0013sub@yopmail.com,1,0,937.0
...,...,...,...,...
9663,zubir@yopmail.com,1,0,1064.0
9664,zxc@yopmail.com,1,0,1064.0
9665,zxcv@yopmail.com,1,0,1667.0
9666,zxcvb@yopmail.com,1,0,1064.0
9667,zxcvzdhjcvdskjcvzcf@yopmail.com,1,0,1671.0

In [27]:
catcher_login= catcher_df.merge(login_df, 
                                on='jobma_catcher_email',
                                how='left')

In [28]:
catcher_login.drop('jobma_catcher_email', axis=1, inplace=True)

# Wallet_df##############

In [29]:
catcher_login.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [30]:
wallet_df.replace('', 0, inplace=True)

In [31]:
wallet_df = wallet_df.groupby('catcher_id').agg(wallet_sum=('wallet_amount', 'sum'),
                                                plan_type=('plan_type', 'first'),
                                                is_unlimited=('is_unlimited', 'max')
                                                ).reset_index()

In [32]:
wallet_df=wallet_df.astype(int)

In [33]:
catcher_login_wallet=catcher_login.merge(wallet_df, 
                                         on='catcher_id',
                                         how='left')

In [34]:
catcher_df.shape, login_df.shape, wallet_df.shape, catcher_login_wallet.shape, subscription_df.shape

((4466, 13), (9668, 4), (4479, 4), (4466, 18), (9493, 34))

# Subscription DF

In [35]:
subscription_df.head(2)

,id,catcher_id,catcher_username,catcher_email,sub_user_id,subscription_id,premium_plan_id,premium_plan,transaction_id,subscription_amount,...,e_invoice,cheque_number,banker,cheque_amount,cheque_image,cancel_date,invoice_suffix,radioGstValue,created_at,updated_at
0,3,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",9BY60034LB809061M,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:47:12,2021-06-11 12:41:24
1,4,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",3KH319283K655734K,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:52:28,2021-06-11 12:41:24

In [36]:
subscription_df = subscription_df.groupby('catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                                            subscription_count=('subscription_amount', 'count'),
                                                            ).reset_index()
subscription_df['subscription_sum'] = subscription_df['subscription_sum'].where(subscription_df['subscription_sum'] > 0, 0)

In [37]:
catcher_login_wallet_subs = catcher_login_wallet.merge(subscription_df, 
                                                       on='catcher_id',
                                                       how='left')

In [38]:
subscription_df.shape, catcher_login_wallet_subs.shape

((4477, 3), (4466, 20))

# Pre recorded Kit

In [39]:
pre_recorded_kit_df = pre_recorded_kit_df.groupby('catcher_id').size().reset_index(name='pre_recorded_kit_counts')

In [40]:
catcher_login_wallet_subs_prereckit = catcher_login_wallet_subs.merge(pre_recorded_kit_df, 
                                                                      on='catcher_id',
                                                                      how='left')

In [41]:
pre_recorded_kit_df.shape, catcher_login_wallet_subs_prereckit.shape

((1192, 2), (4466, 21))

# job_posting_df

In [42]:
job_posting_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [43]:
job_posting_df = job_posting_df.groupby('catcher_id').size().reset_index(name='number_of_jobs_posted')

In [44]:
catcher_login_wallet_subs_prereckit_jobposted = catcher_login_wallet_subs_prereckit.merge(job_posting_df, 
                                                                      on='catcher_id',
                                                                      how='left')

In [45]:
catcher_login_wallet_subs_prereckit.shape, catcher_login_wallet_subs_prereckit_jobposted.shape

((4466, 21), (4466, 22))

# invitation df

In [46]:
invitation_df = invitation_df.groupby('jobma_catcher_id').size().reset_index(name='number_of_invitations')

In [47]:
invitation_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [48]:
catcher_login_wallet_subs_prereckit_jobposted_invites = catcher_login_wallet_subs_prereckit_jobposted.merge(invitation_df, 
                                                                                                            on='catcher_id',
                                                                                                            how='left')

In [49]:
catcher_login_wallet_subs_prereckit_jobposted.shape, catcher_login_wallet_subs_prereckit_jobposted_invites.shape

((4466, 22), (4466, 23))

# pitchers_applied_df

In [50]:
pitchers_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [51]:
pitchers_df = pitchers_df.groupby('catcher_id').size().reset_index(name='number_of_pitcher_applied')

In [52]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied = catcher_login_wallet_subs_prereckit_jobposted_invites.merge(pitchers_df, 
                                                                                                                             on='catcher_id',
                                                                                                                             how='left')

In [53]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied.shape

(4466, 24)

# pre_rec_interviews_df.T

In [54]:
pre_rec_interviews_df = pre_rec_interviews_df.groupby('jobma_catcher_id').size().reset_index(name='pre_rec_interviews_counts')

In [55]:
pre_rec_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [56]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied.merge(pre_rec_interviews_df, 
                                                                                                                                            on='catcher_id',
                                                                                                                                            how='left')

In [57]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec.shape

(4466, 25)

# live_interviews_df

In [58]:
live_interviews_df = live_interviews_df.groupby('jobma_catcher_id').size().reset_index(name='live_interviews_counts')

In [59]:
live_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [60]:
live_interviews_df.shape

(57, 2)

In [61]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec.merge(live_interviews_df, 
                                                                                                                                                       on='catcher_id',
                                                                                                                                                       how='left')

In [62]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live.shape

(4466, 26)

In [63]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live.to_csv("Final_test_db.csv", index=False)

In [64]:
# catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live.to_csv("test_database.csv", index=False) #Erlier used