In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
catcher_df = pd.read_sql("SELECT * FROM jobma_catcher where jobma_catcher_parent=0", engine)
login_df=pd.read_sql("Select * FROM jobma_login", engine)
wallet_df = pd.read_sql("Select * FROM wallet", engine) 
subscription_df = pd.read_sql("Select * FROM subscription_history", engine)

# # #kits created
ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine)#
pre_recorded_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine)

# #job posted and invitation and pitchers
job_posting_df = pd.read_sql("SELECT * FROM jobma_employer_job_posting", engine)
invitation_df = pd.read_sql("Select * FROM jobma_pitcher_invitations", engine)
pitchers_df = pd.read_sql("SELECT * FROM jobma_pitcher_applied_jobs", engine) 

# #candidate interview response data, #just for pre-recorded type, # live interview type
pre_rec_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews", engine) 
live_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews_online", engine)
ai_interviews_df = pd.read_sql("SELECT * FROM jobma_ai_interviews", engine)

In [4]:
catcher_df=catcher_df[['jobma_catcher_id',
                        'jobma_catcher_status',
                        'jobma_catcher_type',
                        'subscription_status',#also in wallet table
                        'subscription_type',
                        'referral_credit',
                       'jobma_catcher_email',#for joining in login
                        'is_premium',
                        # 'approval',#null values
                        # 'currency', #Already in subscription and has strong correlation
                        'sub_user',
                        'company_size',
                        'per_sub_user',
                        'created_at',
                        ]].copy()

In [5]:
# Calculating days
catcher_df['created_at'] = pd.to_datetime(catcher_df['created_at'], errors='coerce')
catcher_df['created_at'] = (pd.Timestamp('today') - catcher_df['created_at']).dt.days

In [6]:
catcher_df['jobma_catcher_status'] = (
    catcher_df['jobma_catcher_status']
    .replace(['-1', ' '], 0)
    .fillna(0)
    .astype(int)
)
catcher_df['subscription_status'] = catcher_df['subscription_status'].replace('0', 1).astype(int)

In [7]:
catcher_df.loc[catcher_df['referral_credit'] > 0, 'referral_credit'] = 1

In [8]:
catcher_df['is_premium'] = catcher_df['is_premium'].replace('', 0).astype(int)

In [9]:
catcher_df['jobma_catcher_type'].isna().sum()

np.int64(167)

In [10]:
mean_catcher = catcher_df['jobma_catcher_type'].astype(float).mean()
catcher_df['jobma_catcher_type'] = catcher_df['jobma_catcher_type'].fillna(mean_catcher).astype(int)

In [11]:
catcher_df.drop('created_at', axis=1, inplace=True)

In [12]:
catcher_df['company_size'].isna().sum()

np.int64(1055)

In [13]:
catcher_df['company_size'] = catcher_df['company_size'].fillna(catcher_df['company_size'].mode()[0])

In [14]:
catcher_df['sub_user'] = catcher_df['sub_user'].clip(upper=1000)

In [15]:
catcher_df['per_sub_user'].value_counts()

per_sub_user
100                3114
10000              1062
60                 1052
["60","100"]        152
12000               127
80                   25
500                  11
["10000","100"]       2
90                    1
Name: count, dtype: int64

In [16]:
def convert_per_sub_user_avg(value):
    try:
        if isinstance(value, str) and value.startswith('['):
            parsed = ast.literal_eval(value)
            return sum(int(v) for v in parsed) / len(parsed)
        return int(value)
    except:
        return None

catcher_df['per_sub_user'] = catcher_df['per_sub_user'].apply(convert_per_sub_user_avg)

In [17]:
catcher_df['per_sub_user'].value_counts()

per_sub_user
100.0      3114
10000.0    1062
60.0       1052
12000.0     127
80.0         25
500.0        11
90.0          1
Name: count, dtype: int64

In [18]:
catcher_df.isna().sum()

jobma_catcher_id          0
jobma_catcher_status      0
jobma_catcher_type        0
subscription_status       0
subscription_type         0
referral_credit           0
jobma_catcher_email       0
is_premium                0
sub_user                  0
company_size              0
per_sub_user            154
dtype: int64

# Login

In [19]:
login_df[['jobma_last_login', 'created_at']] = login_df[['jobma_last_login', 'created_at']].apply(pd.to_datetime, errors='coerce')
login_df['days_since_login'] = (pd.Timestamp('today') - login_df['jobma_last_login']).dt.days
login_df['days_since_creation'] = (pd.Timestamp('today') - login_df['created_at']).dt.days

In [20]:
login_df['jobma_login_status'] = login_df['jobma_login_status'].replace(['', None], 0).astype(int)

In [21]:
login_df = login_df.groupby('jobma_user_name').agg(number_of_logins=('jobma_user_name', 'count'),
                                                   jobma_login_status=('jobma_login_status', 'max'),
                                                   days_since_login=('days_since_login', 'max'),
                                                   days_since_creation=('days_since_creation', 'max')
                                                  ).reset_index()

In [22]:
login_mean = login_df['days_since_login'].mean()
login_df['days_since_login'] = login_df['days_since_login'].fillna(login_df['days_since_creation'])
login_df['days_since_login'] = login_df['days_since_login'].fillna(login_mean)

In [23]:
login_df.drop('days_since_creation', axis=1, inplace=True)

In [24]:
login_df.rename(columns={'jobma_user_name': 'jobma_catcher_email'}, inplace=True)

In [25]:
catcher_login= catcher_df.merge(login_df, 
                                on='jobma_catcher_email',
                                how='left')

In [26]:
catcher_login['number_of_logins'] = catcher_login['number_of_logins'].clip(upper=5)

In [27]:
catcher_login.drop('jobma_catcher_email', axis=1, inplace=True)

In [28]:
catcher_login.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

# Wallet

In [29]:
wallet_df.replace('', 0, inplace=True)

In [30]:
wallet_df = wallet_df.groupby('catcher_id').agg(
    wallet_sum=('wallet_amount', 'sum'),
    plan_type=('plan_type', 'max'),
    is_unlimited=('is_unlimited', 'max'),
    # subscription_type=('subscription_type', 'max')#already in catcher and has strong correlation
).reset_index()

In [31]:
wallet_df.isna().sum()

catcher_id      0
wallet_sum      0
plan_type       0
is_unlimited    0
dtype: int64

In [32]:
wallet_df=wallet_df.astype(int)

In [33]:
catcher_login_wallet=catcher_login.merge(wallet_df, 
                                         on='catcher_id',
                                         how='left')

# Subscription

In [34]:
subscription_df = subscription_df.groupby('catcher_id').agg(
    subscription_sum=('subscription_amount', 'sum'),
    subscription_count=('subscription_amount', 'count'),
    currency=('currency', 'max'),
    premium_plan_id=('premium_plan_id', 'max'),
).reset_index()

In [35]:
subscription_df.isna().sum()

catcher_id             0
subscription_sum       0
subscription_count     0
currency               0
premium_plan_id       33
dtype: int64

In [36]:
subscription_df['subscription_sum'] = subscription_df['subscription_sum'].where(subscription_df['subscription_sum'] > 0, 0)

In [37]:
catcher_login_wallet_subs = catcher_login_wallet.merge(subscription_df, 
                                                       on='catcher_id',
                                                       how='left')

In [38]:
catcher_login_wallet_subs.shape

(5546, 20)

# Pre recorded Kit

In [39]:
pre_recorded_kit_df = pre_recorded_kit_df.groupby('catcher_id').size().reset_index(name='pre_recorded_kit_counts')

In [40]:
catcher_login_wallet_subs_prereckit = catcher_login_wallet_subs.merge(pre_recorded_kit_df, 
                                                                      on='catcher_id',
                                                                      how='left')

In [41]:
catcher_login_wallet_subs_prereckit.shape

(5546, 21)

# job_posting

In [42]:
job_posting_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [43]:
job_posting_df = job_posting_df.groupby('catcher_id').size().reset_index(name='number_of_jobs_posted')

In [44]:
catcher_login_wallet_subs_prereckit_jobposted = catcher_login_wallet_subs_prereckit.merge(job_posting_df, 
                                                                      on='catcher_id',
                                                                      how='left')

In [45]:
job_posting_df

      catcher_id  number_of_jobs_posted
0              0                      2
1             92                    825
2             96                     40
3             97                      3
4             99                    163
...          ...                    ...
1287        9413                      2
1288        9415                      1
1289        9433                      1
1290        9443                      1
1291     6184445                      1

[1292 rows x 2 columns]

In [46]:
catcher_login_wallet_subs_prereckit_jobposted.shape

(5546, 22)

# invitation

In [47]:
invitation_df = invitation_df.groupby('jobma_catcher_id').size().reset_index(name='number_of_invitations')

In [48]:
invitation_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [49]:
catcher_login_wallet_subs_prereckit_jobposted_invites = catcher_login_wallet_subs_prereckit_jobposted.merge(invitation_df, 
                                                                                                            on='catcher_id',
                                                                                                            how='left')

In [50]:
invitation_df

      catcher_id  number_of_invitations
0              0                     34
1             92                      7
2            446                      1
3            746                      8
4            872                      4
...          ...                    ...
1013        9415                      6
1014        9429                      2
1015        9431                      3
1016        9433                      1
1017        9443                     11

[1018 rows x 2 columns]

In [51]:
catcher_login_wallet_subs_prereckit_jobposted_invites.shape

(5546, 23)

# pitchers_df

In [52]:
pitchers_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [53]:
pitchers_df = pitchers_df.groupby('catcher_id').size().reset_index(name='number_of_pitcher_applied')

In [54]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied = catcher_login_wallet_subs_prereckit_jobposted_invites.merge(pitchers_df, 
                                                                                                                             on='catcher_id',
                                                                                                                             how='left')

In [55]:
pitchers_df

     catcher_id  number_of_pitcher_applied
0           0.0                          1
1          92.0                      17640
2          96.0                          3
3          97.0                          2
4          99.0                         67
..          ...                        ...
951      9325.0                          2
952      9365.0                          5
953      9403.0                         10
954      9415.0                          4
955      9431.0                          1

[956 rows x 2 columns]

In [56]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied.shape

(5546, 24)

# pre_rec_interviews

In [57]:
pre_rec_interviews_df = pre_rec_interviews_df.groupby('jobma_catcher_id').size().reset_index(name='pre_rec_interviews_counts')

In [58]:
pre_rec_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [59]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied.merge(pre_rec_interviews_df, 
                                                                                                                                            on='catcher_id',
                                                                                                                                            how='left')

In [60]:
pre_rec_interviews_df

     catcher_id  pre_rec_interviews_counts
0             0                         14
1            51                         15
2            92                          3
3           127                         28
4           141                          2
..          ...                        ...
860        9325                          4
861        9365                          7
862        9403                         10
863        9415                          1
864        9431                          1

[865 rows x 2 columns]

In [61]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec.shape

(5546, 25)

# live_interviews

In [62]:
live_interviews_df = live_interviews_df.groupby('jobma_catcher_id').size().reset_index(name='live_interviews_counts')

In [63]:
live_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [64]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec.merge(live_interviews_df, 
                                                                                                                                                       on='catcher_id',
                                                                                                                                                       how='left')

In [65]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live.shape

(5546, 26)

In [66]:
live_interviews_df

     catcher_id  live_interviews_counts
0            92                       2
1           446                       1
2           720                       1
3           746                      10
4           908                      14
..          ...                     ...
116        8873                       1
117        8891                       7
118        9315                       6
119        9333                       1
120        9415                       3

[121 rows x 2 columns]

# ai_video_kit

In [67]:
ai_video_kit_df = ai_video_kit_df.groupby('catcher_id').size().reset_index(name='ai_kit_counts')

In [68]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live.merge(ai_video_kit_df,
                                                                                                                                                                 on='catcher_id',
                                                                                                                                                                 how='left')

In [69]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit.shape

(5546, 27)

In [70]:
ai_video_kit_df

   catcher_id  ai_kit_counts
0        1873             32
1        6543              1
2        8565              4
3        8597              1
4        8873             10
5        9265              1
6        9299              1
7        9313              1
8        9443              1

# ai_interviews_df

In [71]:
ai_interviews_df = ai_interviews_df.groupby('jobma_catcher_id').size().reset_index(name='ai_interviews_counts')

In [72]:
ai_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [73]:
ai_interviews_df

   catcher_id  ai_interviews_counts
0        1873                    67
1        8597                     5
2        9299                     2

In [74]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit_aiinterview = catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit.merge(ai_interviews_df,
                                                                                                                                                                                      on='catcher_id',
                                                                                                                                                                                      how='left')

In [75]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit_aiinterview.shape

(5546, 28)

In [76]:
catcher_df.shape, login_df.shape, catcher_login.shape,  wallet_df.shape, catcher_login_wallet.shape

((5546, 11), (38484, 4), (5546, 13), (5560, 4), (5546, 16))

In [77]:
subscription_df.shape, ai_video_kit_df.shape, ai_interviews_df.shape,

((5560, 5), (9, 2), (3, 2))

In [78]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit_aiinterview

,catcher_id,jobma_catcher_status,jobma_catcher_type,subscription_status,subscription_type,referral_credit,is_premium,sub_user,company_size,per_sub_user,...,currency,premium_plan_id,pre_recorded_kit_counts,number_of_jobs_posted,number_of_invitations,number_of_pitcher_applied,pre_rec_interviews_counts,live_interviews_counts,ai_kit_counts,ai_interviews_counts
0,92,1,1,2,0,0,1,999,1-25,100.0,...,0,3.0,2.0,825.0,7.0,17640.0,3.0,2.0,NaN,NaN
1,106,0,0,2,0,0,1,999,1-25,100.0,...,0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,124,1,0,2,0,0,1,999,1-25,100.0,...,0,3.0,NaN,1.0,NaN,3.0,NaN,NaN,NaN,NaN
3,125,1,0,2,0,0,1,999,1-25,100.0,...,0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,126,1,0,2,0,0,1,999,1-25,100.0,...,0,3.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5541,9319,1,1,1,0,0,0,999,1-25,100.0,...,1,4.0,1.0,400.0,1.0,1.0,1.0,NaN,NaN,NaN
5542,9365,1,1,1,0,0,1,21,26-100,100.0,...,0,2.0,NaN,4.0,25.0,5.0,7.0,NaN,NaN,NaN
5543,9405,1,1,1,0,0,0,999,1-25,100.0,...,1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5544,9413,1,1,1,0,0,0,10,101-500,100.0,...,0,3.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN
5545,9445,1,1,1,0,0,0,10,1-25,100.0,...,0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit_aiinterview.isna().sum()

catcher_id                      0
jobma_catcher_status            0
jobma_catcher_type              0
subscription_status             0
subscription_type               0
referral_credit                 0
is_premium                      0
sub_user                        0
company_size                    0
per_sub_user                  154
number_of_logins               13
jobma_login_status             13
days_since_login               13
wallet_sum                      3
plan_type                       3
is_unlimited                    3
subscription_sum                2
subscription_count              2
currency                        2
premium_plan_id                35
pre_recorded_kit_counts      4643
number_of_jobs_posted        4627
number_of_invitations        4840
number_of_pitcher_applied    4929
pre_rec_interviews_counts    4965
live_interviews_counts       5471
ai_kit_counts                5539
ai_interviews_counts         5543
dtype: int64

In [80]:
df=catcher_login_wallet_subs_prereckit_jobposted_invites_papplied_prerec_live_aikit_aiinterview.copy()

In [81]:
def fill_missing_values(df):
    for col in df.columns:
        if df[col].dtype == 'int64':
            df[col] = df[col].fillna(0)
        elif df[col].dtype == 'float64':
            df[col] = df[col].fillna(0.0)
        elif df[col].dtype == 'object':
            if not df[col].mode().empty:
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna('others')
    return df

df = fill_missing_values(df)

In [82]:
df.isna().sum()

catcher_id                   0
jobma_catcher_status         0
jobma_catcher_type           0
subscription_status          0
subscription_type            0
referral_credit              0
is_premium                   0
sub_user                     0
company_size                 0
per_sub_user                 0
number_of_logins             0
jobma_login_status           0
days_since_login             0
wallet_sum                   0
plan_type                    0
is_unlimited                 0
subscription_sum             0
subscription_count           0
currency                     0
premium_plan_id              0
pre_recorded_kit_counts      0
number_of_jobs_posted        0
number_of_invitations        0
number_of_pitcher_applied    0
pre_rec_interviews_counts    0
live_interviews_counts       0
ai_kit_counts                0
ai_interviews_counts         0
dtype: int64

In [83]:
df.to_csv("development.csv", index=False)

In [84]:
print("Done")

Done