In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
#candidate interview response data
pre_rec_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews", engine) #just for pre-recorded type
live_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews_online", engine)# live interview type
ai_interviews_df = pd.read_sql("SELECT * FROM jobma_ai_interviews", engine)

In [3]:
pre_rec_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)
live_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)
ai_interviews_df.rename(columns={"jobma_catcher_id":"catcher_id"}, inplace=True)

In [4]:
pre_rec_interviews_df = pre_rec_interviews_df.groupby('catcher_id').size().reset_index(name='pre_rec_interviews_counts')

In [5]:
pre_rec_interviews_df

     catcher_id  pre_rec_interviews_counts
0             0                         14
1            51                         15
2            92                          3
3           127                         28
4           141                          2
..          ...                        ...
860        9325                          4
861        9365                          7
862        9403                         10
863        9415                          1
864        9431                          1

[865 rows x 2 columns]

In [6]:
live_interviews_df = live_interviews_df.groupby('catcher_id').size().reset_index(name='live_interviews_counts')

In [7]:
live_interviews_df

     catcher_id  live_interviews_counts
0            92                       2
1           446                       1
2           720                       1
3           746                      10
4           908                      14
..          ...                     ...
116        8873                       1
117        8891                       7
118        9315                       6
119        9333                       1
120        9415                       3

[121 rows x 2 columns]

In [8]:
ai_interviews_df = ai_interviews_df.groupby('catcher_id').size().reset_index(name='ai_interviews_counts')

In [9]:
ai_interviews_df

   catcher_id  ai_interviews_counts
0        1873                    67
1        8597                     5
2        9299                     2

In [10]:
pre_rec_interviews_df.to_csv("pre_rec_interviews_df.csv", index=False)
live_interviews_df.to_csv("live_interviews_df.csv", index=False)
ai_interviews_df.to_csv("ai_interviews_df.csv", index=False)