In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
#Usage or how recursively client is using our plateform
jobma_pitcher_invitations_df = pd.read_sql("SELECT * FROM jobma_pitcher_invitations", engine)

In [3]:
jobma_pitcher_invitations_df.shape

(54691, 48)

In [4]:
jobma_pitcher_invitations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54691 entries, 0 to 54690
Data columns (total 48 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 54691 non-null  int64
 1   jobma_post_id                      54691 non-null  int64
 2   jobma_catcher_id                   54691 non-null  int64
 3   jobma_pitcher_id                   54691 non-null  int64
 4   applied_id                         22088 non-null  float64
 5   is_invited                         54691 non-null  object
 6   jobma_pitcher_email                54691 non-null  object
 7   jobma_invitation_date              54691 non-null  object
 8   jobma_invitation_expire_date       53962 non-null  object
 9   interview_start_time               6993 non-null   object
 10  interview_end_time                 6768 non-null   object
 11  invitation_timezone                54691 non-null  object
 12  jobma_invitation_message           54691 non-null  object
 13  jobma_interview_round              28382 non-null  float64
 14  stages                             50614 non-null  float64
 15  jobma_interview_mode               54691 non-null  object
 16  jobma_interview_room               54691 non-null  object
 17  jobma_interview_token              8756 non-null   object
 18  pre_recorded_token                 53573 non-null  object
 19  jobma_interview_status             54691 non-null  object
 20  assessment_kit_id                  49905 non-null  float64
 21  assessment_question_set            48624 non-null  object
 22  pre_screening                      717 non-null    object
 23  pre_screen_qualify                 698 non-null    object
 24  application_settings               29440 non-null  object
 25  practice_question                  1259 non-null   object
 26  interview_type                     54691 non-null  object
 27  answer_duration                    31761 non-null  object
 28  interview_time_lapse               54691 non-null  int64
 29  interview_complete_notified_email  829 non-null    object
 30  jobseeker_signup_confirmation      54691 non-null  int64
 31  signup_form_options                13060 non-null  object
 32  can_request_retake                 54691 non-null  int64
 33  active                             54691 non-null  object
 34  prerecorded_email_notification     3969 non-null   object
 35  br_id                              46548 non-null  float64
 36  integration_source                 7 non-null      object
 37  callback_url                       15451 non-null  object
 38  acceptation                        54691 non-null  object
 39  reject_reason                      336 non-null    object
 40  auto_send_reminder_max             54691 non-null  int64
 41  interview_platform_status          54691 non-null  object
 42  source                             1553 non-null   object
 43  live_interview_source              1546 non-null   object
 44  live_interview_data                1142 non-null   object
 45  deleted_at                         8448 non-null   datetime64[ns]
 46  created_at                         54691 non-null  datetime64[ns]
 47  updated_at                         54691 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(5), int64(8), object(32)
memory usage: 20.0+ MB

In [5]:
# Check for duplicate count
print("No of duplicate ---", jobma_pitcher_invitations_df['jobma_catcher_id'].duplicated().sum())

#top most duplicates
print("Top duplicated ----")
print(jobma_pitcher_invitations_df['jobma_catcher_id'].value_counts().head(10))

No of duplicate --- 53673
Top duplicated ----
jobma_catcher_id
2335    3396
924     2811
2266    2624
1873    2539
7151    2262
2169    1820
2334    1731
6411    1612
1839    1397
6139    1393
Name: count, dtype: int64

In [6]:
jobma_pitcher_invitations_df.isna().sum().sort_values(ascending=False)

integration_source                   54684
reject_reason                        54355
pre_screen_qualify                   53993
pre_screening                        53974
interview_complete_notified_email    53862
live_interview_data                  53549
practice_question                    53432
live_interview_source                53145
source                               53138
prerecorded_email_notification       50722
interview_end_time                   47923
interview_start_time                 47698
deleted_at                           46243
jobma_interview_token                45935
signup_form_options                  41631
callback_url                         39240
applied_id                           32603
jobma_interview_round                26309
application_settings                 25251
answer_duration                      22930
br_id                                 8143
assessment_question_set               6067
assessment_kit_id                     4786
stages                                4077
pre_recorded_token                    1118
jobma_invitation_expire_date           729
id                                       0
jobma_catcher_id                         0
jobma_pitcher_id                         0
is_invited                               0
jobma_pitcher_email                      0
jobma_invitation_date                    0
jobma_interview_mode                     0
jobma_invitation_message                 0
invitation_timezone                      0
jobma_post_id                            0
jobma_interview_status                   0
interview_time_lapse                     0
interview_type                           0
jobma_interview_room                     0
jobseeker_signup_confirmation            0
acceptation                              0
active                                   0
can_request_retake                       0
auto_send_reminder_max                   0
interview_platform_status                0
created_at                               0
updated_at                               0
dtype: int64

In [7]:
jobma_pitcher_invitations_df

,id,jobma_post_id,jobma_catcher_id,jobma_pitcher_id,applied_id,is_invited,jobma_pitcher_email,jobma_invitation_date,jobma_invitation_expire_date,interview_start_time,...,acceptation,reject_reason,auto_send_reminder_max,interview_platform_status,source,live_interview_source,live_interview_data,deleted_at,created_at,updated_at
0,4,20743,1412,61342,40146.0,1,test8763@yopmail.com,2019-02-14 04:25:33,2019-03-16 00:00:00,None,...,1,None,0,0,None,None,None,2019-02-26 15:33:46,2019-02-14 04:25:33,2021-07-07 11:49:41
1,8,21038,1520,60950,40153.0,1,testpriya1@yopmail.com,2019-02-15 01:39:29,2019-03-17 00:00:00,None,...,1,None,0,0,None,None,None,NaT,2019-02-15 01:39:29,2021-07-07 11:49:41
2,12,21115,1371,60180,NaN,1,kunals@yopmail.com,2019-02-15 03:33:21,2019-03-17 00:00:00,None,...,3,None,0,0,None,None,None,NaT,2019-02-15 03:33:21,2023-06-28 09:35:40
3,16,21119,1371,59775,NaN,1,sanjay@yopmail.com,2019-02-15 04:49:51,2019-03-17 00:00:00,None,...,3,None,0,0,None,None,None,NaT,2019-02-15 04:49:51,2023-06-28 09:35:40
4,20,21121,1582,60992,40160.0,1,account1@yopmail.com,2019-02-18 03:53:03,2019-03-20 00:00:00,None,...,1,None,0,0,None,None,None,2019-02-26 14:37:58,2019-02-18 03:53:03,2021-07-07 11:49:41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54686,577755,35851,9443,1127211,NaN,2,fe@fre.yet,2025-04-02 00:00:00,2025-04-07 23:59:00,None,...,3,None,0,1,None,0,None,NaT,2025-04-02 09:48:14,2025-04-02 15:18:16
54687,577759,0,6184,1121245,NaN,1,kamboj235235007@yopmail.com,2025-04-03 00:00:00,2025-04-07 23:59:00,None,...,3,None,0,1,None,0,None,NaT,2025-04-03 10:51:04,2025-04-03 10:51:22
54688,577763,35851,9443,1126789,NaN,2,few@few.few,2025-04-03 00:00:00,2025-04-08 23:59:00,None,...,3,None,0,1,None,0,None,NaT,2025-04-03 05:37:10,2025-04-03 11:07:11
54689,577767,35857,1873,1127225,NaN,2,gerd@gr.grs,2025-04-03 00:00:00,2025-04-08 23:59:00,None,...,3,None,0,1,None,0,None,NaT,2025-04-03 09:18:17,2025-04-03 14:48:19
54690,577771,33421,1873,1127229,NaN,1,employerjobma14@mailinator.com,2025-04-03 16:30:00,2025-04-03 17:00:00,2025-04-03 16:30:00,...,1,None,0,0,0,0,,NaT,2025-04-03 10:30:42,2025-04-03 10:30:42

In [8]:
jobma_pitcher_invitations_selected_df = jobma_pitcher_invitations_df[[#'id', 
                                                                      # 'jobma_post_id', 
                                                                      'jobma_catcher_id', #@1018
                                                                      # 'jobma_pitcher_id', #@33197
                                                                      # 'applied_id', #@18519
                                                                      
                                                                      # 'is_invited', #1,2,-
                                                                      # 'jobma_pitcher_email',
                                                                      # 'jobma_invitation_date', 
                                                                      # 'jobma_invitation_expire_date',
           
                                                                      # 'interview_start_time', #Usage time-------------######------------------Interaction with candidate
                                                                      # 'interview_end_time', #Usage time---------------######----------------Interaction with candidate
                                                                      # 'invitation_timezone',#asia,colombo
           
                                                                      # 'jobma_invitation_message', 
                                                                      # 'jobma_interview_round', #nan, 1.0 2.0.....8#################----------------------------------------------------------------??
                                                                      # 'stages',############0,1,2,3-------------------------------------------------------------------------------------------------??
           
                                                                      # 'jobma_interview_mode', #1,2,3,4,0------------------------
                                                                      # 'jobma_interview_room', #0
                                                                      # 'jobma_interview_token',#tokens mostly none
           
                                                                      # 'pre_recorded_token', #-, None
                                                                      # 'jobma_interview_status', ############3,2,4,0,1,6,5,- @8
                                                                      # 'assessment_kit_id',#idd
           
                                                                      # 'assessment_question_set', #question set used as intro, jr python developer @9806 object value
                                                                      # 'pre_screening', #@83 Questionss
                                                                      # 'pre_screen_qualify',#1,0,2
           
                                                                      # 'application_settings', ###############@2415 Settings turned on by client is important feature#########
                                                                      # 'practice_question', 
                                                                      # 'interview_type',#@5,          ###1,2,3,4,----------->>
           
                                                                      # 'answer_duration', #####################answer duration for interaction of client how much time client spends and about candidate knowledge
                                                                      # 'interview_time_lapse',######@0325   0,60,10,,20,120,
           
                                                                      # 'interview_complete_notified_email', #eamil to confirm
                                                                      # 'jobseeker_signup_confirmation', #0,1-->0
           
                                                                      # 'signup_form_options', #lot of value
                                                                      # 'can_request_retake', #@2   0,1
                                                                      # 'active', #0,1
           
                                                                      # 'prerecorded_email_notification', #email notifications
                                                                      # 'br_id', ###@34, 0.0, 58.0, 74.0
                                                                      # 'integration_source', #1
           
                                                                      # 'callback_url', #url giving to callback
                                                                      # 'acceptation', ######################3,1,2 mostly 3
                                                                      #'reject_reason',#####################None, 1, 2--------------------------------------------------------??
           
                                                                      # 'auto_send_reminder_max', #####@6        0,1,3,2,9,22
                                                                      # 'interview_platform_status', #####@2   0,1
                                                                      # 'source',#########@4,    None,0,2,1
           
                                                                      # 'live_interview_source', #None, 0, 1---->None
                                                                      # 'live_interview_data',###################@88   dictionary
                                                                      
                                                                      # 'deleted_at',
                                                                      # 'created_at', 
                                                                      # 'updated_at'
                                                                       ]].copy()

In [9]:
jobma_pitcher_invitations_selected_df.isna().sum()

jobma_catcher_id    0
dtype: int64

In [10]:
jobma_pitcher_invitations_selected_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [11]:
jobma_pitcher_invitations_df.shape, jobma_pitcher_invitations_selected_df.shape

((54691, 48), (54691, 1))

In [12]:
jobma_pitcher_invitations_selected_df['number_of_invitations'] = jobma_pitcher_invitations_selected_df['catcher_id'].map(jobma_pitcher_invitations_selected_df['catcher_id'].value_counts())

In [13]:
jobma_pitcher_invitations_selected_df.head(50)

    catcher_id  number_of_invitations
0         1412                    290
1         1520                     63
2         1371                    244
3         1371                    244
4         1582                     11
5         1520                     63
6          924                   2811
7         1652                      6
8         1652                      6
9          924                   2811
10        1374                     12
11         924                   2811
12         924                   2811
13        1412                    290
14        1650                     18
15        1650                     18
16        1520                     63
17        1520                     63
18        1652                      6
19         924                   2811
20        1520                     63
21        1520                     63
22         924                   2811
23        1520                     63
24        1520                     63
25        1520                     63
26        1520                     63
27        1520                     63
28        1520                     63
29        1520                     63
30        1598                     14
31        1412                    290
32        1582                     11
33        1582                     11
34        1648                      1
35        1592                     13
36        1520                     63
37        1520                     63
38        1412                    290
39        1602                     11
40        1584                     18
41        1598                     14
42        1584                     18
43        1591                      8
44        1591                      8
45        1654                      3
46        1598                     14
47         924                   2811
48         924                   2811
49        1655                     12

In [14]:
jobma_pitcher_invitations_selected_df.shape

(54691, 2)

In [15]:
jobma_pitcher_invitations_selected_df.drop_duplicates(inplace=True)

In [16]:
jobma_pitcher_invitations_selected_df.shape

(1018, 2)

In [17]:
jobma_pitcher_invitations_selected_df.to_csv("invitation_df.csv", index=False)