In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
jobma_login_df = pd.read_sql("SELECT * FROM jobma_login", engine) #Usage details
jobma_catcher_df = pd.read_sql("SELECT * FROM jobma_catcher", engine) #Usage details
jobma_login_df.shape, jobma_catcher_df.shape

((39321, 21), (7672, 75))

In [4]:
jobma_login_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39321 entries, 0 to 39320
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   jobma_login_id       39321 non-null  int64
 1   jobma_user_name      39321 non-null  object
 2   jobma_password       39321 non-null  object
 3   jobma_role_id        39321 non-null  int64
 4   jobma_user_id        39321 non-null  int64
 5   jobma_last_login     37785 non-null  object
 6   jobma_created_by     7854 non-null   object
 7   confirmed            39321 non-null  int64
 8   confirmation_code    39321 non-null  object
 9   jobma_login_status   7924 non-null   object
 10  jobma_login_ip       39321 non-null  object
 11  forget_password      245 non-null    object
 12  remember_token       39321 non-null  object
 13  jobma_social_login   39321 non-null  int64
 14  password_changed_at  39321 non-null  datetime64[ns]
 15  deleted_at           84 non-null     datetime64[ns]
 16  created_at           39321 non-null  object
 17  updated_at           39321 non-null  object
 18  google2fa_secret     0 non-null      object
 19  two_factor_status    39321 non-null  object
 20  two_factor_type      39321 non-null  object
dtypes: datetime64[ns](2), int64(5), object(14)
memory usage: 6.3+ MB

In [5]:
jobma_login_df.isna().sum()

jobma_login_id             0
jobma_user_name            0
jobma_password             0
jobma_role_id              0
jobma_user_id              0
jobma_last_login        1536
jobma_created_by       31467
confirmed                  0
confirmation_code          0
jobma_login_status     31397
jobma_login_ip             0
forget_password        39076
remember_token             0
jobma_social_login         0
password_changed_at        0
deleted_at             39237
created_at                 0
updated_at                 0
google2fa_secret       39321
two_factor_status          0
two_factor_type            0
dtype: int64

In [6]:
jobma_login_df.isna().sum().sort_values(ascending=False).head(7)

google2fa_secret      39321
deleted_at            39237
forget_password       39076
jobma_created_by      31467
jobma_login_status    31397
jobma_last_login       1536
jobma_user_id             0
dtype: int64

In [7]:
jobma_login_df.T

,0,1,2,3,4,5,6,7,8,9,...,39311,39312,39313,39314,39315,39316,39317,39318,39319,39320
jobma_login_id,1,240,535,642,993,1009,1096,4015,4237,4261,...,112375,112377,112379,112381,112383,112385,112387,112389,112391,112393
jobma_user_name,existinguser@example.com,superadmin@mailinator.com,gaurava@selectsourceintl.com,SMandeep@selectsourceintl.com,ywangb13@gmail.com,teresamcf@gmail.com,hr@3spl.in,krishnak@dtawave.com,aviationindustry@job4u.com,joboportunities@job4u.com,...,pratikabc5@yopmail.com,nayan223@yopmail.com,pratikabc6@yopmail.com,pratikabc7@yopmail.com,pratikabc8@yopmail.com,pratikabc9@yopmail.com,pratikabc10@yopmail.com,ramesh23@yopmail.com,ramesh21@yopmail.com,Sergebrian@yopmail.com
jobma_password,hashedpassword,$2y$10$TyEFO2DlIqVuwnpn1yDRUeRjIklsTP6Rkiq09sn...,$2y$10$WEnjfOt4vTnq/x50aYNaE.zDrr4F00EB37NnnYC...,$2y$10$Lj1NrtAvq0KSPu4VM4/sAOUaq1UCHYf0zo1xbcF...,2982087bec56338d021c81e0bac623a0,76514888624f3db0c43bb828aef91e69,9dccb99534e38083094e4c1a6ff9459f,$2y$10$y9VI/kPvMdvac0Iz.xcvYuQaTVqPMH3rOY6rLMD...,8616b2fac1570dcadd8388e0a21e7f90,8616b2fac1570dcadd8388e0a21e7f90,...,$2b$10$e1C0RgXnmfwGzY39uxzyYuHWUAN/4JvRvAeIWV6...,$2b$10$AfL4D5iXcAtQL5sPbG6g0OFNSP4aJmvStbmx8zp...,$2b$10$.FFYBR0cdqdEou94.YXIeOZdsOFO2I1F0naveE/...,$2b$10$Ph1owj5gGiEX4byahOIetO1HK32kgaVYCYtO6p4...,$2b$10$tecdc/h1iDgC3a4F4fq61OTatR0v8QhRBFnSipn...,$2b$10$VmMPRrRKW61t4mTIWcovr.dguenWGVUEGmYGUOE...,$2b$10$6A5AUWsFx86xHxgYH.eFG.FdyuzcdQrmatTv8IP...,$2b$10$pBYHn72SXg4RULY5rV1L0uhRQOmcueI.g3OZDbm...,$2b$10$tG9Uy9StD4OOPfR7ZeTyR.TLgmrjZSxP5zqWPFp...,$2y$10$p9mNtOk4sjZJU7EMIMiqjeesQf5jvUzvVSYgDNQ...
jobma_role_id,4,1,5,5,4,4,3,5,3,3,...,4,4,4,4,4,4,4,4,4,3
jobma_user_id,1001,162,96,557,908,924,106,117,124,125,...,1126997,1127007,1127067,1127069,1127071,1127089,1127091,1127093,1127095,9445
jobma_last_login,None,2024-10-18 07:38:58,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,2020-02-05 23:09:03,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,...,2025-03-26 07:40:51,None,None,None,None,None,None,2025-03-26 12:57:28,None,0000-00-00 00:00:00
jobma_created_by,None,0,0,1,1,1,0,1,0,0,...,None,None,None,None,None,None,None,None,None,1
confirmed,1,1,0,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
confirmation_code,1,,,,,,,,,,...,1,1,1,1,1,1,1,1,1,
jobma_login_status,0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
jobma_login_ip,,,,,,,,,,,...,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,
forget_password,1,None,0,1,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
remember_token,,N52TQOQ1aR3iA8VVC269FnEFApjJM3M1QqW0BOquGr6cIH...,UBzEkXCpiagAdQiZvHDSMxbu0lQZy3cicuRIf5pFXZWknT...,K5qiDGmZ4UhgBtz94isKfNXo3R01Pi4EJx9AwwyXIrBWjE...,,,,,,,...,,,,,,,,,,
jobma_social_login,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
password_changed_at,2020-10-30 03:57:14,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,...,2025-03-21 11:58:13,2025-03-21 16:27:57,2025-03-26 16:08:17,2025-03-26 16:12:42,2025-03-26 16:14:49,2025-03-26 16:55:35,2025-03-26 16:56:55,2025-03-26 17:26:35,2025-03-26 18:28:10,2025-03-28 10:45:12
deleted_at,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
created_at,2024-09-26 16:21:36,0000-00-00 00:00:00,2016-11-23 20:53:27,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,...,2025-03-21 06:28:14,2025-03-21 10:57:58,2025-03-26 10:38:17,2025-03-26 10:42:43,2025-03-26 10:44:49,2025-03-26 11:25:35,2025-03-26 11:26:56,2025-03-26 11:56:36,2025-03-26 12:58:10,2025-03-28 05:15:12
updated_at,2024-09-26 16:21:36,2024-10-18 07:38:58,2017-05-09 18:06:45,2018-02-09 01:02:45,0000-00-00 00:00:00,2020-02-05 23:09:03,2019-11-12 05:35:02,2017-09-20 02:04:49,2019-11-13 05:28:04,2019-11-13 05:28:04,...,2025-03-21 06:28:14,2025-03-21 10:57:58,2025-03-26 10:38:17,2025-03-26 10:42:43,2025-03-26 10:44:49,2025-03-26 11:25:35,2025-03-26 11:26:56,2025-03-26 11:56:36,2025-03-26 12:58:10,2025-03-28 05:15:12
google2fa_secret,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
two_factor_status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
two_factor_type,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
jobma_login_df.nunique()

jobma_login_id         39321
jobma_user_name        38484
jobma_password         38519
jobma_role_id              7
jobma_user_id          38637
jobma_last_login       18232
jobma_created_by           3
confirmed                  2
confirmation_code       2838
jobma_login_status         3
jobma_login_ip          3179
forget_password            2
remember_token          5299
jobma_social_login         2
password_changed_at    29403
deleted_at                35
created_at             36902
updated_at             36448
google2fa_secret           0
two_factor_status          2
two_factor_type            2
dtype: int64

In [9]:
jobma_login_df['jobma_login_id'].value_counts()

jobma_login_id
112393    1
1         1
240       1
535       1
642       1
         ..
6591      1
6138      1
4691      1
4320      1
4261      1
Name: count, Length: 39321, dtype: int64

In [10]:
jobma_login_df['jobma_user_id'].value_counts()

jobma_user_id
0          470
1115527     35
1115509     19
1115275     15
1115355     11
          ...
1127089      1
1127091      1
1127093      1
1127095      1
117          1
Name: count, Length: 38637, dtype: int64

In [11]:
jobma_login_df.columns

Index(['jobma_login_id', 'jobma_user_name', 'jobma_password', 'jobma_role_id',
       'jobma_user_id', 'jobma_last_login', 'jobma_created_by', 'confirmed',
       'confirmation_code', 'jobma_login_status', 'jobma_login_ip',
       'forget_password', 'remember_token', 'jobma_social_login',
       'password_changed_at', 'deleted_at', 'created_at', 'updated_at',
       'google2fa_secret', 'two_factor_status', 'two_factor_type'],
      dtype='object')

In [12]:
# Check for duplicate jobma_user_id count
print("No of duplicate catcher_id ----", jobma_login_df['jobma_user_name'].duplicated().sum())

#top most duplicates
print("Top duplicated jobma_user_id ----")
print(jobma_login_df['jobma_user_name'].value_counts().head(10))

No of duplicate catcher_id ---- 837
Top duplicated jobma_user_id ----
jobma_user_name
                                        468
thisisemail1423143ww4@mailinator.com     35
nameee                                   25
thisisemail123434@mailinator.com         19
stringasdgh@yopmail.com                  15
dummy@yopmail.com                        11
sssrs123pkmkb@yopmail.com                11
thisisemail1231434@mailinator.com         8
test287382@yopmail.com                    8
tets283782@yopmail.com                    8
Name: count, dtype: int64

In [13]:
column_data = jobma_login_df['jobma_user_name']
print(jobma_login_df.shape)
print("No of unique values----",column_data.nunique(dropna=False), "\n")
print("Unique values ---------",column_data.unique(), "\n")
print(column_data.value_counts(dropna=False).head(10), "\n")

(39321, 21)
No of unique values---- 38484

Unique values --------- ['existinguser@example.com' 'superadmin@mailinator.com'
 'gaurava@selectsourceintl.com' ... 'pratikabc10@yopmail.com'
 'ramesh23@yopmail.com' 'ramesh21@yopmail.com']

jobma_user_name
                                        468
thisisemail1423143ww4@mailinator.com     35
nameee                                   25
thisisemail123434@mailinator.com         19
stringasdgh@yopmail.com                  15
dummy@yopmail.com                        11
sssrs123pkmkb@yopmail.com                11
thisisemail1231434@mailinator.com         8
test287382@yopmail.com                    8
tets283782@yopmail.com                    8
Name: count, dtype: int64

In [14]:
jobma_login_selected_df=jobma_login_df[[#'jobma_login_id',        #@39321 id
                                        'jobma_user_name',       # name
                                        # 'jobma_password',        # password
                                        'jobma_role_id',         #@7, 4,3,5,0,9,1,2 id----------------------------->>
                                        'jobma_user_id',         # id
                                        # 'jobma_last_login',      #@18233 almost 0000.000, None--------------------->> 
                                        # 'jobma_created_by',      #@4, NOne, 1, 0, 2-------------------------------->>
                                        'confirmed',             # 0,1-----1
                                        # 'confirmation_code',     #mostly null and email...
                                        # 'jobma_login_status',    #@4  -,0,1----------------------------------------->>
                                        # 'jobma_login_ip',        
                                        # 'forget_password',       
                                        # 'remember_token',        
                                        # 'jobma_social_login',    #2,  0,1---->0
                                        # 'password_changed_at',   
                                        # 'deleted_at',            #39237 is NAt value----------------------------------------------->>required all below three columns to know tenure of client
                                        # 'created_at',            ##---------------------------------------------------------------->> to find user tenure
                                        # 'updated_at',            ##----------------------------------------------------------------->>
                                        # 'google2fa_secret',      
                                        # 'two_factor_status',     #@0,1----->0
                                        # 'two_factor_type'        #@0,1----->0
                                       ]].copy()

In [15]:
jobma_login_selected_df

                     jobma_user_name  jobma_role_id  jobma_user_id  confirmed
0           existinguser@example.com              4           1001          1
1          superadmin@mailinator.com              1            162          1
2       gaurava@selectsourceintl.com              5             96          0
3      SMandeep@selectsourceintl.com              5            557          0
4                 ywangb13@gmail.com              4            908          1
...                              ...            ...            ...        ...
39316         pratikabc9@yopmail.com              4        1127089          1
39317        pratikabc10@yopmail.com              4        1127091          1
39318           ramesh23@yopmail.com              4        1127093          1
39319           ramesh21@yopmail.com              4        1127095          1
39320         Sergebrian@yopmail.com              3           9445          1

[39321 rows x 4 columns]

In [16]:
jobma_login_selected_df['number_of_logins'] = jobma_login_selected_df['jobma_user_name'].map(jobma_login_selected_df['jobma_user_name'].value_counts())

In [17]:
jobma_login_selected_df

,jobma_user_name,jobma_role_id,jobma_user_id,confirmed,number_of_logins
0,existinguser@example.com,4,1001,1,1
1,superadmin@mailinator.com,1,162,1,1
2,gaurava@selectsourceintl.com,5,96,0,1
3,SMandeep@selectsourceintl.com,5,557,0,2
4,ywangb13@gmail.com,4,908,1,1
...,...,...,...,...,...
39316,pratikabc9@yopmail.com,4,1127089,1,1
39317,pratikabc10@yopmail.com,4,1127091,1,1
39318,ramesh23@yopmail.com,4,1127093,1,1
39319,ramesh21@yopmail.com,4,1127095,1,1
39320,Sergebrian@yopmail.com,3,9445,1,3

In [18]:
jobma_login_selected_df.shape, jobma_login_df.shape

((39321, 5), (39321, 21))

In [19]:
jobma_login_selected_df.head(10)

,jobma_user_name,jobma_role_id,jobma_user_id,confirmed,number_of_logins
0,existinguser@example.com,4,1001,1,1
1,superadmin@mailinator.com,1,162,1,1
2,gaurava@selectsourceintl.com,5,96,0,1
3,SMandeep@selectsourceintl.com,5,557,0,2
4,ywangb13@gmail.com,4,908,1,1
5,teresamcf@gmail.com,4,924,1,1
6,hr@3spl.in,3,106,1,1
7,krishnak@dtawave.com,5,117,1,1
8,aviationindustry@job4u.com,3,124,1,1
9,joboportunities@job4u.com,3,125,1,1

In [20]:
jobma_catcher_df=jobma_catcher_df[['jobma_catcher_id','jobma_catcher_email']]

In [21]:
jobma_catcher_df.rename(columns={'jobma_catcher_email': 'jobma_user_name'}, inplace=True)

In [22]:
jobma_catcher_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [23]:
jobma_catcher_df

      catcher_id                jobma_user_name
0              1         jayant_kks@yopmail.com
1             92      jobs@selectsourceintl.com
2             96   gaurava@selectsourceintl.com
3            106                     hr@3spl.in
4            117           krishnak@dtawave.com
...          ...                            ...
7667        9437      ownDataNew12312@jobma.com
7668        9439   checkEvaluate12312@jobma.com
7669        9441  sessionChange312312@jobma.com
7670        9443         nayan23@mailinator.com
7671        9445         Sergebrian@yopmail.com

[7672 rows x 2 columns]

In [24]:
jobma_login_df= jobma_catcher_df.merge(jobma_login_selected_df,
                                       on='jobma_user_name',
                                       how='outer')

In [25]:
jobma_login_df.shape

(39946, 6)

In [26]:
jobma_login_df

,catcher_id,jobma_user_name,jobma_role_id,jobma_user_id,confirmed,number_of_logins
0,987.0,,5.0,890.0,0.0,468.0
1,987.0,,0.0,0.0,0.0,468.0
2,987.0,,0.0,0.0,0.0,468.0
3,987.0,,0.0,0.0,0.0,468.0
4,987.0,,0.0,0.0,0.0,468.0
...,...,...,...,...,...,...
39941,NaN,zxdfhbd@yopmail.com,4.0,62961.0,1.0,1.0
39942,NaN,zxncbew42q43@mailinator.com,4.0,1112244.0,1.0,1.0
39943,NaN,zz@yopmail.com,4.0,86818.0,1.0,1.0
39944,NaN,zzzzzrrrr@yopmail.com,4.0,79731.0,1.0,1.0
39945,NaN,Àbh8@mailinator.com,4.0,80790.0,0.0,1.0

In [27]:
jobma_login_df=jobma_login_df[['catcher_id', 'confirmed', 'number_of_logins']]

In [28]:
jobma_login_df

       catcher_id  confirmed  number_of_logins
0           987.0        0.0             468.0
1           987.0        0.0             468.0
2           987.0        0.0             468.0
3           987.0        0.0             468.0
4           987.0        0.0             468.0
...           ...        ...               ...
39941         NaN        1.0               1.0
39942         NaN        1.0               1.0
39943         NaN        1.0               1.0
39944         NaN        1.0               1.0
39945         NaN        0.0               1.0

[39946 rows x 3 columns]

In [29]:
jobma_catcher_df.duplicated().sum()

np.int64(0)

In [30]:
jobma_login_df.duplicated().sum()

np.int64(32233)

In [31]:
jobma_login_df.drop_duplicates(inplace=True)

C:\Users\SSI\AppData\Local\Temp\ipykernel_11016\3717868385.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobma_login_df.drop_duplicates(inplace=True)

In [32]:
jobma_login_df.shape, jobma_catcher_df.shape

((7713, 3), (7672, 2))

In [33]:
jobma_login_df.isna().sum()

catcher_id          19
confirmed           36
number_of_logins    36
dtype: int64

In [34]:
8760-1066, 7694-7672

(7694, 22)

In [35]:
jobma_login_df.dropna(inplace=True)

C:\Users\SSI\AppData\Local\Temp\ipykernel_11016\2917073290.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobma_login_df.dropna(inplace=True)

In [36]:
jobma_login_df.shape

(7658, 3)

In [41]:
jobma_login_df=jobma_login_df.astype(int)

In [42]:
jobma_login_df.isna().sum()

catcher_id          0
confirmed           0
number_of_logins    0
dtype: int64

In [43]:
jobma_login_df.nunique(dropna=False)

catcher_id          7636
confirmed              2
number_of_logins       6
dtype: int64

In [44]:
jobma_login_df

       catcher_id  confirmed  number_of_logins
0             987          0               468
468          5270          0               468
940          8422          1                 1
941          8423          1                 1
943          8424          1                 1
...           ...        ...               ...
39929        7180          1                 1
39935        7141          1                 1
39937        3850          1                 1
39938        7172          1                 1
39939        3735          1                 1

[7658 rows x 3 columns]

In [51]:
jobma_login_df['number_of_logins'].unique()

array([468,   1,   2,   3,   4,   5])

In [45]:
jobma_login_df.to_csv("login_df.csv", index=False)