# jobma_subscription_df
#how much frequently using 
#subscription history, total purchase

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")
jobma_subscription_history_df = pd.read_sql("SELECT * FROM subscription_history", engine)

In [4]:
jobma_subscription_history_df.shape

(11049, 34)

In [5]:
jobma_subscription_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11049 entries, 0 to 11048
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   11049 non-null  int64
 1   catcher_id           11049 non-null  int64
 2   catcher_username     8072 non-null   object
 3   catcher_email        7390 non-null   object
 4   sub_user_id          967 non-null    float64
 5   subscription_id      11049 non-null  int64
 6   premium_plan_id      10927 non-null  float64
 7   premium_plan         10929 non-null  object
 8   transaction_id       11049 non-null  object
 9   subscription_amount  11049 non-null  float64
 10  credit_given         11049 non-null  int64
 11  paypal_profile_id    11049 non-null  object
 12  paypal_payer_id      11049 non-null  object
 13  expiry_date          11049 non-null  object
 14  currency             11049 non-null  object
 15  premium_storage      11049 non-null  int64
 16  igst                 11049 non-null  int64
 17  cgst                 11049 non-null  int64
 18  gst_code             4957 non-null   object
 19  currency_val         11049 non-null  float64
 20  recurring_data       11049 non-null  object
 21  payment_mode         11049 non-null  object
 22  status               11049 non-null  object
 23  payment_status       11049 non-null  object
 24  e_invoice            11049 non-null  object
 25  cheque_number        666 non-null    object
 26  banker               666 non-null    object
 27  cheque_amount        11049 non-null  float64
 28  cheque_image         8 non-null      object
 29  cancel_date          0 non-null      object
 30  invoice_suffix       11049 non-null  int64
 31  radioGstValue        11049 non-null  int64
 32  created_at           11049 non-null  datetime64[ns]
 33  updated_at           11049 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(5), int64(9), object(18)
memory usage: 2.9+ MB

In [6]:
# # Check for duplicatewho has taken subscription many times whish shows frequent use
# print("No of duplicate catcher_id ----", jobma_subscription_history_df['catcher_id'].duplicated().sum())

# # duplicates
# print("Top duplicated catcher_ids are")
# print(jobma_subscription_history_df['catcher_id'].value_counts().head(10))

In [7]:
jobma_subscription_history_df.columns

Index(['id', 'catcher_id', 'catcher_username', 'catcher_email', 'sub_user_id',
       'subscription_id', 'premium_plan_id', 'premium_plan', 'transaction_id',
       'subscription_amount', 'credit_given', 'paypal_profile_id',
       'paypal_payer_id', 'expiry_date', 'currency', 'premium_storage', 'igst',
       'cgst', 'gst_code', 'currency_val', 'recurring_data', 'payment_mode',
       'status', 'payment_status', 'e_invoice', 'cheque_number', 'banker',
       'cheque_amount', 'cheque_image', 'cancel_date', 'invoice_suffix',
       'radioGstValue', 'created_at', 'updated_at'],
      dtype='object')

In [8]:
# column_data = jobma_subscription_history_df['payment_status']
# print(jobma_subscription_history_df.shape)
# print("No of unique values----", column_data.nunique(dropna=False))
# print("Unique values ---------", column_data.unique(), "\n")
# print(column_data.value_counts(dropna=False).head(10))

In [9]:
# jobma_subscription_history_selected_df=jobma_subscription_history_df[[#'id',  # starts from 2
#                                                                       'catcher_id',  # duplicated catcher id as has buy many times
#                                                                       # 'catcher_username', 
#                                                                       # 'catcher_email', 
#                                                                       # 'sub_user_id',  #@407 unique values,  sub users and admins too many with same id----------------->>
#                                                                       'subscription_id',  # 1,2------------------------------------------------------------------------>>
#                                                                       'premium_plan_id',  #@10    1.0,2.0,3.0....10.0------------------------------------>>3.0,2.0 mostly
#                                                                       'premium_plan',  #@802 unique but dict------------ category of different different plans............??
#                                                                       # 'transaction_id',
#                                                                       'subscription_amount',  # diffrenet may be taken bu client--plan prices ----->May be................??
#                                                                       'credit_given',  #@37,   0,50,600,.................................How much credits they got on buying
#                                                                       # 'paypal_profile_id',
#                                                                       # 'paypal_payer_id',
#                                                                       # 'expiry_date',
#                                                                       'currency',  # 0,1-------------------------------------------------------------meaning of 0 ,1--------??
#                                                                       # 'premium_storage',#----------------------------------------------------------all are 0...............??
#                                                                       # 'igst',
#                                                                       # 'cgst',
#                                                                       # 'gst_code',
#                                                                       'currency_val',  #@39,   1, 70 mostly 1 and 70-------------------------------------------------------->>
#                                                                       # 'recurring_data',  # Categorial data #Text data
#                                                                       'payment_mode',#@7, unique['1' '2' '3' '5' '' '6' '4'] , mostly 1,6,3
#                                                                       'status',  #1,0 iska nahi pta hai---------------------------------------------------------------------->>
#                                                                       'payment_status',#1,0-----------------------------------------------------------------------mostly 1--->>
#                                                                       'e_invoice',
#                                                                       # 'cheque_number',
#                                                                       # 'banker',
#                                                                       # 'cheque_amount',
#                                                                       # 'cheque_image',
#                                                                       # 'cancel_date',
#                                                                       # 'invoice_suffix',
#                                                                       # 'radioGstValue',
#                                                                       # 'created_at',
#                                                                       # 'updated_at'
#                                                                      ]].copy()

In [ ]:
# jobma_subscription_history_selected_df.corr(numeric_only=True).T

In [ ]:
# jobma_subscription_history_selected_df['times_of_subscription'] = jobma_subscription_history_selected_df['catcher_id'].map(jobma_subscription_history_selected_df['catcher_id'].value_counts())

In [30]:
subscription_df=jobma_subscription_history_df[['id',
                                               'catcher_id',
                                               # 'premium_plan',
                                               'subscription_amount',  # diffrenet may be taken bu client--plan prices ----->May be................??
                                               'credit_given',  #@37,   0,50,600,.................................How much credits they got on buying
                                               # 'currency',  # 0,1-------------------------------------------------------------meaning of 0 ,1--------??
                                               # 'premium_storage',#----------------------------------------------------------all are 0...............??
                                               'currency_val',
                                               'status',  #1,0 iska nahi pta hai---------------------------------------------------------------------->>
                                               'payment_status',#1,0-----------------------------------------------------------------------mostly 1--->>
                                              ]]

In [31]:
subscription_df.isna().sum()

id                     0
catcher_id             0
subscription_amount    0
credit_given           0
currency_val           0
status                 0
payment_status         0
dtype: int64

In [32]:
jobma_subscription_history_df.shape, subscription_df.shape

((11049, 34), (11049, 7))

In [33]:
subscription_df

,id,catcher_id,subscription_amount,credit_given,currency_val,status,payment_status
0,2,899,0.0,0,1.0,0,0
1,3,900,0.0,0,1.0,0,0
2,4,900,0.0,0,1.0,0,0
3,5,900,0.0,0,1.0,0,0
4,6,900,0.0,0,1.0,0,0
...,...,...,...,...,...,...,...
11044,11589,7099,10000.0,0,1.0,0,1
11045,11591,9299,50.0,0,1.0,1,1
11046,11593,7099,25000.0,150,1.0,1,1
11047,11595,8565,5000.0,0,1.0,1,1
11048,11597,9445,0.0,150,0.0,1,1

In [34]:
subscription_df.duplicated().sum()

np.int64(0)

In [35]:
subscription_df['times_of_subscription'] = subscription_df['catcher_id'].map(subscription_df['catcher_id'].value_counts())

C:\Users\SSI\AppData\Local\Temp\ipykernel_18440\3421878776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subscription_df['times_of_subscription'] = subscription_df['catcher_id'].map(subscription_df['catcher_id'].value_counts())

In [36]:
subscription_df

,id,catcher_id,subscription_amount,credit_given,currency_val,status,payment_status,times_of_subscription
0,2,899,0.0,0,1.0,0,0,2
1,3,900,0.0,0,1.0,0,0,8
2,4,900,0.0,0,1.0,0,0,8
3,5,900,0.0,0,1.0,0,0,8
4,6,900,0.0,0,1.0,0,0,8
...,...,...,...,...,...,...,...,...
11044,11589,7099,10000.0,0,1.0,0,1,10
11045,11591,9299,50.0,0,1.0,1,1,2
11046,11593,7099,25000.0,150,1.0,1,1,10
11047,11595,8565,5000.0,0,1.0,1,1,3
11048,11597,9445,0.0,150,0.0,1,1,1

In [39]:
subscription_df=subscription_df[['catcher_id', 'subscription_amount', 'credit_given', 'currency_val', 'times_of_subscription']]

In [40]:
subscription_df.duplicated().sum()

np.int64(3114)

In [42]:
subscription_df.drop_duplicates(inplace=True)

In [43]:
subscription_df.shape

(7935, 5)

In [44]:
subscription_df

,catcher_id,subscription_amount,credit_given,currency_val,times_of_subscription
0,899,0.0,0,1.0,2
1,900,0.0,0,1.0,8
9,901,0.0,0,1.0,4
10,903,0.0,0,1.0,6
12,904,0.0,0,1.0,6
...,...,...,...,...,...
11042,1873,5000.0,5000,1.0,238
11043,9413,150.0,150,1.0,1
11045,9299,50.0,0,1.0,2
11047,8565,5000.0,0,1.0,3
11048,9445,0.0,150,0.0,1

In [45]:
subscription_df.to_csv("subscription_df1.csv", index=False)

In [ ]:
import seaborn as sns

In [ ]:
# sns.heatmap(jobma_subscription_history_selected_df.corr(numeric_only=True), annot=True)

In [ ]:
# jobma_subscription_history_selected_df.to_csv("subscription_df.csv", index=False)