In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
df = pd.read_sql("SELECT * FROM wallet", engine)

In [4]:
df.shape

(5562, 14)

In [5]:
df.head()

,id,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,premium_storage,trial_account_type,gst_code,billing_cycle,billing_cycle_status,created_at,updated_at
0,1,669,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 12:10:27,2017-11-03 12:10:27
1,2,92,NaN,34.0,0,0,0,0,0.0,None,None,0,2017-11-03 12:10:27,2020-02-20 07:10:00
2,3,898,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 04:36:27,2017-11-03 04:36:27
3,4,912,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 14:08:57,2017-11-03 14:08:57
4,5,92,NaN,3.0,0,0,0,0,0.0,None,None,0,2017-11-03 14:08:57,2020-02-20 07:10:00

In [6]:
df = df.groupby('catcher_id').agg(wallet_sum=('wallet_amount', 'sum'),
                                  subscription_type=('subscription_type', 'first'),
                                  plan_type=('plan_type', 'max'),
                                  is_unlimited=('is_unlimited', 'max')
                                 ).reset_index()

In [7]:
df

      catcher_id  wallet_sum subscription_type plan_type is_unlimited
0             92        37.0                 0         0            0
1            106         0.0                 0         0            0
2            124         0.0                 0         0            0
3            125         0.0                 0         0            0
4            126         0.0                 0         0            0
...          ...         ...               ...       ...          ...
5555        9319    500000.0                 0         0            1
5556        9365       137.0                 0         0            0
5557        9405    500000.0                 0         0            1
5558        9413     15000.0                 0         0            0
5559        9445       150.0                 0         0            0

[5560 rows x 5 columns]

In [8]:
df.isna().sum()

catcher_id           0
wallet_sum           0
subscription_type    0
plan_type            0
is_unlimited         0
dtype: int64

In [9]:
df.to_csv("new_final_wallet_df.csv", index=False)