In [1]:
#working on kits to combine them and use them

In [2]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine)
pre_recorded_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine)

In [4]:
ai_video_kit_df.head(5)

,id,catcher_id,title,slug,answer_duration,question_set,min_experience,max_experience,interview_level,evaluation_keywords,is_active,deleted_at,created_at,updated_at
0,13,1873,Jquery,jquery,300,"[{""id"":""1"",""ques"":""Added question""},{""id"":""2"",...",0,2,2,"[""Python"", ""Jquery"", ""Laravel""]",1,None,2024-10-15 05:22:46,2024-10-15 05:22:46
1,14,1873,React,react-4,1800,"[{""id"":""1"",""ques"":""Can you explain what React ...",1,3,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:23:49,2024-10-15 05:23:49
2,15,1873,Kit,kit,300,"[{""id"":""1"",""ques"":""Can you explain what React ...",2,6,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:31:13,2024-10-15 05:31:13
3,16,1873,Python,python,1200,"[{""id"":""1"",""ques"":""Can you explain the differe...",29,50,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:33:12,2024-10-15 05:33:12
4,17,1873,Javascript,javascript,300,"[{""id"":""1"",""ques"":""Can you explain the differe...",1,3,2,"[""Coding Skills""]",1,None,2024-10-15 05:44:30,2024-10-15 05:44:30

In [5]:
pre_recorded_kit_df.head(5)

,id,catcher_id,title,slug,answer_duration,interview_type,question_set,pre_screening,ques_ids,weightage,...,offer_status,sr_id,main_sr_id,node_id,random_ques,random_options,is_streaming,deleted_at,created_at,updated_at
0,3,908,test,test-2,NaN,1,"{""question"":[{""ques"":""intro"",""ques_title"":"""",""...",None,3_416,0,...,None,None,0,None,0,0,1,None,2018-08-14 03:39:20,2023-10-05 04:52:21
1,5,1209,A@1,aat1,NaN,1,"{""question"":[{""ques"":""intro"",""ques_title"":"""",""...",None,3_419,0,...,None,None,0,None,1,0,1,None,2018-08-14 06:58:32,2023-10-05 04:52:21
2,13,1209,test integ,test-integ,NaN,1,"{""question"":[{""ques"":""intro"",""ques_title"":"""",""...",None,"1_550,1_478,1_477,5_106",0,...,None,None,0,None,0,0,1,None,2018-08-20 05:59:43,2023-10-05 04:52:21
3,16,1209,test454667,test454667,NaN,1,"{""question"":[{""ques"":""intro"",""ques_title"":"""",""...",None,"1_566,1_478,1_477,5_106",0,...,None,None,0,None,1,0,1,None,2018-08-21 06:07:08,2023-10-05 04:52:21
4,22,1209,test555,test555,NaN,1,"{""question"":[{""ques"":""intro"",""ques_title"":"""",""...",None,"1_589,1_478,1_477,5_106",0,...,None,None,0,None,0,0,1,None,2018-08-23 08:49:51,2023-10-05 04:52:21

In [7]:
pre_recorded_kit_df.shape, ai_video_kit_df.shape

((5852, 27), (52, 14))

In [8]:
# Group by catcher_id and sum answer_duration
ai_video_kit_df = ai_video_kit_df.groupby('catcher_id').size().reset_index(name='ai_kit_counts')

In [9]:
ai_video_kit_df

   catcher_id  ai_kit_counts
0        1873             32
1        6543              1
2        8565              4
3        8597              1
4        8873             10
5        9265              1
6        9299              1
7        9313              1
8        9443              1

In [10]:
ai_video_kit_df.nunique()

catcher_id       9
ai_kit_counts    4
dtype: int64

In [11]:
pre_recorded_kit_df = pre_recorded_kit_df.groupby('catcher_id').size().reset_index(name='pre_recorded_kit_counts')

In [12]:
pre_recorded_kit_df

      catcher_id  pre_recorded_kit_counts
0              0                       17
1              1                       96
2             92                        2
3            151                        1
4            207                        1
...          ...                      ...
1077        9413                        1
1078        9415                        1
1079        9433                        1
1080        9443                        1
1081        9579                        1

[1082 rows x 2 columns]

In [13]:
pre_recorded_kit_df.nunique()

catcher_id                 1082
pre_recorded_kit_counts      60
dtype: int64

In [14]:
pre_recorded_kit_df.shape

(1082, 2)

In [16]:
pre_recorded_kit_df.max()

catcher_id                 9579
pre_recorded_kit_counts     297
dtype: int64

In [19]:
ai_video_kit_df.max()

catcher_id       9443
ai_kit_counts      32
dtype: int64

In [21]:
ai_video_kit_df.isna().sum()

catcher_id       0
ai_kit_counts    0
dtype: int64

In [22]:
pre_recorded_kit_df.isna().sum()

catcher_id                 0
pre_recorded_kit_counts    0
dtype: int64

In [23]:
pre_recorded_kit_df.to_csv("pre_recorded_kits_df.csv", index=False)

In [24]:
ai_video_kit_df.to_csv("ai_video_kits_df.csv", index=False)