# jobma_employer_job_posting
#Positions created by the client for job posting

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
df = pd.read_sql("SELECT * FROM jobma_employer_job_posting", engine)

In [3]:
df.shape

(16742, 72)

In [9]:
# df.info()

In [5]:
# jobma_employer_job_posting_selected_df = jobma_employer_job_posting_df[[#'jobma_job_post_id',,
#                                                                         'jobma_catcher_id', ############1292 unique values in it
#                                                                         # 'taleo_job_id', #196 unique id
#                                                                         # 'job_assessment_kit_id',#
#                                                                         # 'ai_live_kit_id', #Mostly null 0.0,17.0,1698.0.... @6
#                                                                         # 'jobma_job_title', #Job titles as new job, job by position,timed,new,
#                                                                         # 'slug',#######sameas title but more
#                                                                         # 'jobma_job_description', #May be job descriptions
#                                                                         # 'jobma_job_notes', #notes adding for candidate @27
#                                                                         # 'jobma_job_type',#@14, contract,permanent,part time, intern
   
#                                                                         # 'job_dur_year', #@12, 0.0,1.0...16
#                                                                         # # # 'job_dur_month', 
#                                                                         # # 'jobma_job_min_exp',########minimum experience may be used for prescreening or min exp
#                                                                         # 'jobma_job_max_exp', ######max experience null,0.0.....
#                                                                         # 'jobma_job_min_salary', #####salary offeredn or candidate salary

   
#                                                                         # 'ai_rating_params',
#                                                                         # 'jobma_job_sal_negotiable', #nan, 0.0,1 @2
#                                                                         # 'jobma_job_sal_comments',#rate of sala pay mostly none
#                                                                         # 'jobma_job_qualification', #952 value can be minimized
#                                                                         # 'jobma_job_locations', #job location may be offered
#                                                                         # 'jobma_job_industry',#it, medical, telecommunication..... categorial data
   
#                                                                         # 'jobma_job_functional_areas', #it, eng, biotech etc
#                                                                         # 'jobma_job_keywords',#keywords, pega, analyst, java, development
   
#                                                                         # 'jobma_job_currency',#@12, usd, inr, 1,2,3,4 mostly null
#                                                                         # 'jobma_job_salary_type',#annual, monthly, hourly, weekly
   
#                                                                         # 'jobma_job_recruiter_name', #who recruited.......................>>mostly ssi, ssi
#                                                                         #'jobma_job_recruiter_email',
   
#                                                                         #'jobma_job_recruiter_phone', 
#                                                                         # 'jobma_job_recruiter_ext',#some categorial code 7895,2656 like
   
#                                                                         # 'jobma_job_recruiter_website', 
#                                                                         # 'jobma_job_company_name',
   
#                                                                         # 'jobma_job_company_profile', #intro of cmpy
#                                                                         # 'jobma_job_company_website',
   
#                                                                         # 'jobma_job_company_url_redirect', 
#                                                                         # 'jobma_job_notice_period',#may be used when while reccomendind candidates in future, 0,3,2,4,1,5-->0
   
#                                                                         # 'jobma_job_expiry_date', 
#                                                                         # 'jobma_job_apply_count',#required but nullllll...........>>???
   
#                                                                         # 'jobma_job_view_count', #required but nullllll...........>>???
#                                                                         # 'jobma_job_inactive_date',#date for job inactivity..............................???
   
#                                                                         # 'jobma_job_inactive_reason', #reason for inactivity mostly none, test, ok...
#                                                                         # 'jobma_job_company_show',#0
   
#                                                                         # 'jobma_job_recruiter_show', #0
#                                                                         # 'jobma_job_interview_questions_ids',
   
#                                                                         # 'jobma_question_think_time', 
#                                                                         # 'jobma_question_takes',#can be used in recommender
   
#                                                                         # 'jobma_job_interview_questions_durations', #can be used in recommender 
#                                                                         # 'jobma_job_video_link',#none, yt_link ....
   
#                                                                         # 'jobma_job_video_status', #1, None, null
#                                                                         # 'video_flag', #Can be used in recommender, 0,1,2--->
#                                                                         # 'jobma_job_status',#0,1-->0
   
#                                                                         # 'jobma_job_filename', #none
#                                                                         # 'approval', #1,0,2
#                                                                         # 'jobma_job_paper_ids',#mostly none@31
   
#                                                                         # 'optional_ques', #0
#                                                                         # 'optional_ques_text', #none
#                                                                         # 'job_subscription_status',#1
   
#                                                                         # 'won_source_job_id', #None, 43-9061,51-1011... 
#                                                                         # 'won_profile_name', #None, officeclerk,general..........................>>>>??
#                                                                         # 'won_job_status',  #none, 1 mostly none
   
#                                                                         # 'applicant_count', #nan,0.0,32________________________________________??
#                                                                         # 'is_deleted', #nan, 0.0
#                                                                         # 'is_hot', #0.0, nan, 1.0
#                                                                         # 'source', #0,1 @2
#                                                                         # 'source_id',  #@40, idss
   
#                                                                         # 'is_private_job', #0,1, @3
#                                                                         # 'google_schema',   #, _, 1,   #@2
#                                                                         # 'monster_post_id', #None, @17
#                                                                         # 'bamboo_job_id',#0
                                                                  
#                                                                         # 'created_at', 
#                                                                         # 'updated_at', 
#                                                                         # 'jobma_job_created_date'  #Job creation  date by client
#                                                                        ]].copy()

In [6]:
df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [7]:
df

,jobma_job_post_id,taleo_job_id,catcher_id,job_assessment_kit_id,ai_live_kit_id,jobma_job_title,slug,jobma_job_description,jobma_job_notes,jobma_job_type,...,source,source_id,is_private_job,google_schema,monster_post_id,bamboo_job_id,created_at,updated_at,jobma_job_created_date,ai_rating_params
0,146,0.0,92,0.0,NaN,sr executive human resource leading it company...,sr-executive-human-resource-leading-it-company...,java,,Permanent,...,0,None,0,,None,0,2012-06-08 09:30:00,2023-04-20 12:08:55,2012-06-08 00:00:00,None
1,147,0.0,92,0.0,NaN,business partner training,business-partner-training,java,,Permanent,...,0,None,0,,None,0,2012-06-08 09:30:00,2023-04-20 12:08:55,2012-06-08 00:00:00,None
2,148,0.0,92,0.0,NaN,international sales executive uk based it comp...,international-sales-executive-uk-based-it-comp...,java,,Permanent,...,0,None,0,,None,0,2012-06-08 09:30:00,2023-04-20 12:08:55,2012-06-08 00:00:00,None
3,149,0.0,92,0.0,NaN,executive assistant ceo leading it company gur...,executive-assistant-ceo-leading-it-company-gur...,java,,Permanent,...,0,None,0,,None,0,2012-06-08 09:30:00,2023-04-20 12:08:56,2018-01-16 00:00:00,None
4,150,0.0,92,0.0,NaN,team leader,team-leader,java,,Permanent,...,0,None,0,,None,0,2012-06-08 09:30:00,2023-04-20 12:08:56,2012-06-08 00:00:00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16737,35849,0.0,8597,699323.0,NaN,17 March,17march,<p>qweqweqweqweqwe</p>,None,Contract,...,0,None,0,,None,0,2025-03-17 10:07:32,2025-03-28 13:05:36,2025-03-28 13:05:36,"[""communication"", ""problem-solving"", ""teamwork""]"
16738,35851,0.0,9443,701369.0,131.0,New position,new-position-18,None,None,,...,0,None,0,,None,0,2025-03-26 05:06:35,2025-03-27 09:39:41,2025-03-26 05:06:35,None
16739,35853,0.0,8597,NaN,NaN,April position,april-position,None,None,,...,0,None,0,,None,0,2025-03-31 10:40:17,2025-03-31 10:40:17,2025-03-31 10:40:16,None
16740,35855,0.0,8464,NaN,NaN,jobma,jobma-141,None,None,,...,0,None,0,,None,0,2025-04-02 09:33:54,2025-04-02 09:33:54,2025-04-02 09:33:53,None
16741,35857,0.0,1873,701343.0,NaN,Full Stack Developer,full-stack-developer-6,<p>ASD</p>,None,,...,0,None,0,,None,0,2025-04-03 07:25:01,2025-04-03 07:41:03,2025-04-03 07:41:03,None

In [10]:
df.shape

(16742, 72)

In [11]:
df = df.groupby('catcher_id').size().reset_index(name='number_of_jobs_posted')

In [12]:
df

      catcher_id  number_of_jobs_posted
0              0                      2
1             92                    825
2             96                     40
3             97                      3
4             99                    163
...          ...                    ...
1287        9413                      2
1288        9415                      1
1289        9433                      1
1290        9443                      1
1291     6184445                      1

[1292 rows x 2 columns]

In [13]:
df.to_csv("job_posting_df.csv", index=False)