# jobma_employer_job_posting
#Positions created by the client for job posting

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
jobma_employer_job_posting_df = pd.read_sql("SELECT * FROM jobma_employer_job_posting", engine)

In [3]:
jobma_employer_job_posting_df.shape

(16742, 72)

In [4]:
jobma_employer_job_posting_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16742 entries, 0 to 16741
Data columns (total 72 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   jobma_job_post_id                        16742 non-null  int64
 1   taleo_job_id                             15852 non-null  float64
 2   jobma_catcher_id                         16742 non-null  int64
 3   job_assessment_kit_id                    14587 non-null  float64
 4   ai_live_kit_id                           12 non-null     float64
 5   jobma_job_title                          16742 non-null  object
 6   slug                                     16742 non-null  object
 7   jobma_job_description                    16590 non-null  object
 8   jobma_job_notes                          9498 non-null   object
 9   jobma_job_type                           16742 non-null  object
 10  job_dur_year                             4068 non-null   float64
 11  job_dur_month                            4068 non-null   float64
 12  jobma_job_min_exp                        10557 non-null  float64
 13  jobma_job_max_exp                        10554 non-null  float64
 14  jobma_job_min_salary                     10766 non-null  float64
 15  jobma_job_max_salary                     10763 non-null  float64
 16  jobma_job_sal_negotiable                 4871 non-null   float64
 17  jobma_job_sal_comments                   5445 non-null   object
 18  jobma_job_qualification                  7465 non-null   object
 19  jobma_job_locations                      16742 non-null  object
 20  jobma_job_industry                       16742 non-null  object
 21  jobma_job_functional_areas               16742 non-null  object
 22  jobma_job_keywords                       16742 non-null  object
 23  jobma_job_currency                       16742 non-null  object
 24  jobma_job_salary_type                    9112 non-null   object
 25  jobma_job_recruiter_name                 16742 non-null  object
 26  jobma_job_recruiter_email                16742 non-null  object
 27  jobma_job_recruiter_phone                16742 non-null  object
 28  jobma_job_recruiter_ext                  16742 non-null  object
 29  jobma_job_recruiter_website              11271 non-null  object
 30  jobma_job_company_name                   16742 non-null  object
 31  jobma_job_company_profile                16742 non-null  object
 32  jobma_job_company_website                16742 non-null  object
 33  jobma_job_company_url_redirect           5641 non-null   object
 34  jobma_job_notice_period                  16742 non-null  int64
 35  jobma_job_expiry_date                    16742 non-null  object
 36  jobma_job_apply_count                    0 non-null      object
 37  jobma_job_view_count                     0 non-null      object
 38  jobma_job_inactive_date                  4528 non-null   object
 39  jobma_job_inactive_reason                5506 non-null   object
 40  jobma_job_company_show                   16742 non-null  int64
 41  jobma_job_recruiter_show                 16742 non-null  int64
 42  jobma_job_interview_questions_ids        16742 non-null  object
 43  jobma_question_think_time                16742 non-null  object
 44  jobma_question_takes                     16742 non-null  object
 45  jobma_job_interview_questions_durations  16742 non-null  object
 46  jobma_job_video_link                     9132 non-null   object
 47  jobma_job_video_status                   14235 non-null  object
 48  video_flag                               16742 non-null  object
 49  jobma_job_status                         16742 non-null  int64
 50  jobma_job_filename                       7076 non-null   object
 51  approval                                 16742 non-null  object
 52  jobma_job_paper_ids                      16742 non-null  object
 53  optional_ques                            16742 non-null  int64
 54  optional_ques_text                       16742 non-null  object
 55  job_subscription_status                  16742 non-null  object
 56  won_source_job_id                        121 non-null    object
 57  won_profile_name                         121 non-null    object
 58  won_job_status                           121 non-null    object
 59  applicant_count                          31 non-null     float64
 60  is_deleted                               4068 non-null   float64
 61  is_hot                                   9374 non-null   float64
 62  source                                   16742 non-null  object
 63  source_id                                400 non-null    object
 64  is_private_job                           16742 non-null  object
 65  google_schema                            16742 non-null  object
 66  monster_post_id                          17 non-null     object
 67  bamboo_job_id                            16742 non-null  object
 68  created_at                               16742 non-null  datetime64[ns]
 69  updated_at                               16742 non-null  datetime64[ns]
 70  jobma_job_created_date                   16410 non-null  datetime64[ns]
 71  ai_rating_params                         9 non-null      object
dtypes: datetime64[ns](3), float64(13), int64(7), object(49)
memory usage: 9.2+ MB

In [5]:
jobma_employer_job_posting_selected_df = jobma_employer_job_posting_df[[#'jobma_job_post_id',,
                                                                        'jobma_catcher_id', ############1292 unique values in it
                                                                        # 'taleo_job_id', #196 unique id
                                                                        # 'job_assessment_kit_id',#
                                                                        # 'ai_live_kit_id', #Mostly null 0.0,17.0,1698.0.... @6
                                                                        # 'jobma_job_title', #Job titles as new job, job by position,timed,new,
                                                                        # 'slug',#######sameas title but more
                                                                        # 'jobma_job_description', #May be job descriptions
                                                                        # 'jobma_job_notes', #notes adding for candidate @27
                                                                        # 'jobma_job_type',#@14, contract,permanent,part time, intern
   
                                                                        # 'job_dur_year', #@12, 0.0,1.0...16
                                                                        # # # 'job_dur_month', 
                                                                        # # 'jobma_job_min_exp',########minimum experience may be used for prescreening or min exp
                                                                        # 'jobma_job_max_exp', ######max experience null,0.0.....
                                                                        # 'jobma_job_min_salary', #####salary offeredn or candidate salary

   
                                                                        # 'ai_rating_params',
                                                                        # 'jobma_job_sal_negotiable', #nan, 0.0,1 @2
                                                                        # 'jobma_job_sal_comments',#rate of sala pay mostly none
                                                                        # 'jobma_job_qualification', #952 value can be minimized
                                                                        # 'jobma_job_locations', #job location may be offered
                                                                        # 'jobma_job_industry',#it, medical, telecommunication..... categorial data
   
                                                                        # 'jobma_job_functional_areas', #it, eng, biotech etc
                                                                        # 'jobma_job_keywords',#keywords, pega, analyst, java, development
   
                                                                        # 'jobma_job_currency',#@12, usd, inr, 1,2,3,4 mostly null
                                                                        # 'jobma_job_salary_type',#annual, monthly, hourly, weekly
   
                                                                        # 'jobma_job_recruiter_name', #who recruited.......................>>mostly ssi, ssi
                                                                        #'jobma_job_recruiter_email',
   
                                                                        #'jobma_job_recruiter_phone', 
                                                                        # 'jobma_job_recruiter_ext',#some categorial code 7895,2656 like
   
                                                                        # 'jobma_job_recruiter_website', 
                                                                        # 'jobma_job_company_name',
   
                                                                        # 'jobma_job_company_profile', #intro of cmpy
                                                                        # 'jobma_job_company_website',
   
                                                                        # 'jobma_job_company_url_redirect', 
                                                                        # 'jobma_job_notice_period',#may be used when while reccomendind candidates in future, 0,3,2,4,1,5-->0
   
                                                                        # 'jobma_job_expiry_date', 
                                                                        # 'jobma_job_apply_count',#required but nullllll...........>>???
   
                                                                        # 'jobma_job_view_count', #required but nullllll...........>>???
                                                                        # 'jobma_job_inactive_date',#date for job inactivity..............................???
   
                                                                        # 'jobma_job_inactive_reason', #reason for inactivity mostly none, test, ok...
                                                                        # 'jobma_job_company_show',#0
   
                                                                        # 'jobma_job_recruiter_show', #0
                                                                        # 'jobma_job_interview_questions_ids',
   
                                                                        # 'jobma_question_think_time', 
                                                                        # 'jobma_question_takes',#can be used in recommender
   
                                                                        # 'jobma_job_interview_questions_durations', #can be used in recommender 
                                                                        # 'jobma_job_video_link',#none, yt_link ....
   
                                                                        # 'jobma_job_video_status', #1, None, null
                                                                        # 'video_flag', #Can be used in recommender, 0,1,2--->
                                                                        # 'jobma_job_status',#0,1-->0
   
                                                                        # 'jobma_job_filename', #none
                                                                        # 'approval', #1,0,2
                                                                        # 'jobma_job_paper_ids',#mostly none@31
   
                                                                        # 'optional_ques', #0
                                                                        # 'optional_ques_text', #none
                                                                        # 'job_subscription_status',#1
   
                                                                        # 'won_source_job_id', #None, 43-9061,51-1011... 
                                                                        # 'won_profile_name', #None, officeclerk,general..........................>>>>??
                                                                        # 'won_job_status',  #none, 1 mostly none
   
                                                                        # 'applicant_count', #nan,0.0,32________________________________________??
                                                                        # 'is_deleted', #nan, 0.0
                                                                        # 'is_hot', #0.0, nan, 1.0
                                                                        # 'source', #0,1 @2
                                                                        # 'source_id',  #@40, idss
   
                                                                        # 'is_private_job', #0,1, @3
                                                                        # 'google_schema',   #, _, 1,   #@2
                                                                        # 'monster_post_id', #None, @17
                                                                        # 'bamboo_job_id',#0
                                                                  
                                                                        # 'created_at', 
                                                                        # 'updated_at', 
                                                                        # 'jobma_job_created_date'  #Job creation  date by client
                                                                       ]].copy()

In [6]:
jobma_employer_job_posting_selected_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [7]:
jobma_employer_job_posting_selected_df

       catcher_id
0              92
1              92
2              92
3              92
4              92
...           ...
16737        8597
16738        9443
16739        8597
16740        8464
16741        1873

[16742 rows x 1 columns]

In [8]:
jobma_employer_job_posting_selected_df.shape

(16742, 1)

In [9]:
jobma_employer_job_posting_selected_df.isna().sum()

catcher_id    0
dtype: int64

In [10]:
jobma_employer_job_posting_selected_df['position_created'] = jobma_employer_job_posting_selected_df['catcher_id'].map(jobma_employer_job_posting_selected_df['catcher_id'].value_counts())

In [11]:
jobma_employer_job_posting_selected_df.nunique()

catcher_id          1292
position_created     110
dtype: int64

In [12]:
jobma_employer_job_posting_selected_df.drop_duplicates(inplace=True)

In [13]:
jobma_employer_job_posting_selected_df

       catcher_id  position_created
0              92               825
105            97                 3
123            99               163
124            96                40
461           124                 1
...           ...               ...
16312        6543                 1
16315        9319               400
16718        9415                 1
16720        9433                 1
16738        9443                 1

[1292 rows x 2 columns]

In [14]:
jobma_employer_job_posting_selected_df.to_csv("job_posting_df.csv", index=False)