# jobma_pitcher_applied_jobs Table
#How many jobs he is posting #Pitcher/Candidate details and status.
#Candidate details and status
#Float Value in catcher id

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
jobma_pitcher_applied_jobs_df = pd.read_sql("SELECT * FROM jobma_pitcher_applied_jobs", engine)

In [7]:
jobma_pitcher_applied_jobs_df

,jobma_applied_id,jobma_pitcher_id,jobma_post_id,catcher_id,jobma_applied_date,jobma_contacted_date,jobma_contacted_text,status,tags,jobma_assessment_id,...,avg_ai_score,stages_status,pre_screen_qualify,integration_source,source,export,deleted_rounds,deleted_at,created_at,updated_at
0,154,77463,34345,0.0,2012-06-29 00:00:00,0000-00-00,,0,,0.0,...,NaN,1,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2024-05-16 17:47:20
1,155,1,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,,0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
2,156,355,145,92.0,2012-07-19 00:00:00,0000-00-00,slected,2,"arp,",0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
3,157,354,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,"arp,",0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
4,158,356,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,,0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54

In [4]:
jobma_pitcher_applied_jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54961 entries, 0 to 54960
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   jobma_applied_id               54961 non-null  int64
 1   jobma_pitcher_id               54961 non-null  int64
 2   jobma_post_id                  54961 non-null  int64
 3   catcher_id                     54345 non-null  float64
 4   jobma_applied_date             54961 non-null  object
 5   jobma_contacted_date           54961 non-null  object
 6   jobma_contacted_text           54961 non-null  object
 7   status                         54934 non-null  object
 8   tags                           54961 non-null  object
 9   jobma_assessment_id            34215 non-null  float64
 10  invitation_id                  54961 non-null  int64
 11  documents                      9341 non-null   object
 12  status_name                    54961 non-null  object
 13  pre_recorded_payment_status    54961 non-null  object
 14  live_interview_payment_status  54961 non-null  object
 15  apply_mode                     54961 non-null  object
 16  jobma_interview_rounds         54830 non-null  object
 17  avg_ai_score                   28 non-null     float64
 18  stages_status                  54961 non-null  object
 19  pre_screen_qualify             408 non-null    object
 20  integration_source             2 non-null      object
 21  source                         52938 non-null  object
 22  export                         54961 non-null  object
 23  deleted_rounds                 53 non-null     object
 24  deleted_at                     268 non-null    datetime64[ns]
 25  created_at                     54961 non-null  datetime64[ns]
 26  updated_at                     54961 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(3), int64(4), object(17)
memory usage: 11.3+ MB

In [5]:
jobma_pitcher_applied_jobs_df.isna().sum()

jobma_applied_id                     0
jobma_pitcher_id                     0
jobma_post_id                        0
catcher_id                         616
jobma_applied_date                   0
jobma_contacted_date                 0
jobma_contacted_text                 0
status                              27
tags                                 0
jobma_assessment_id              20746
invitation_id                        0
documents                        45620
status_name                          0
pre_recorded_payment_status          0
live_interview_payment_status        0
apply_mode                           0
jobma_interview_rounds             131
avg_ai_score                     54933
stages_status                        0
pre_screen_qualify               54553
integration_source               54959
source                            2023
export                               0
deleted_rounds                   54908
deleted_at                       54693
created_at                           0
updated_at                           0
dtype: int64

In [8]:
jobma_pitcher_applied_jobs_df.describe().T

,count,mean,min,25%,50%,75%,max,std
jobma_applied_id,54961.0,30550.644457,154.0,14227.0,28344.0,47339.0,65701.0,18788.767255
jobma_pitcher_id,54961.0,91597.584105,0.0,17874.0,31913.0,68939.0,1127227.0,230995.623045
jobma_post_id,54961.0,8579.454995,0.0,763.0,2068.0,21193.0,95062.0,11237.332032
catcher_id,54345.0,1811.22324,0.0,92.0,289.0,2334.0,9431.0,2608.875067
jobma_assessment_id,34215.0,2.656408,0.0,0.0,0.0,0.0,721.0,36.379445
invitation_id,54961.0,43776.553793,0.0,0.0,0.0,0.0,577757.0,139246.426477
avg_ai_score,28.0,63.921429,0.0,29.5,72.5,100.0,100.0,35.056339
deleted_at,268,2024-04-27 04:29:05.541044992,2023-10-03 11:25:22,2024-02-08 00:37:18.500000,2024-05-08 06:51:15.500000,2024-05-30 06:27:04,2025-04-02 09:07:09,NaN
created_at,54961,2019-05-26 01:10:57.697003520,2018-01-24 12:36:09,2018-01-24 12:36:09,2018-01-24 12:36:09,2020-07-31 07:16:43,2025-04-03 10:28:15,NaN
updated_at,54961,2021-12-11 18:58:42.767071744,2021-05-03 18:28:19,2021-07-07 11:48:54,2021-07-07 11:48:54,2022-01-25 16:02:06,2025-04-03 10:28:15,NaN

In [ ]:
jobma_pitcher_applied_jobs_df.duplicated().sum()

In [ ]:
jobma_pitcher_applied_jobs_df['catcher_id'].unique()

In [ ]:
jobma_pitcher_applied_jobs_df['catcher_id'].head(5)

In [ ]:
# Changing data type
jobma_pitcher_applied_jobs_df['catcher_id'] = jobma_pitcher_applied_jobs_df['catcher_id'].fillna(0).astype(int)

In [ ]:
jobma_pitcher_applied_jobs_df['catcher_id'].head(10)

In [ ]:
jobma_pitcher_applied_jobs_selected_df = jobma_pitcher_applied_jobs_df[['jobma_applied_id', #starts from 13
                                                                        # 'jobma_pitcher_id',#59540,59631,59775 likee
                                                                        # 'jobma_post_id',#0,763,759,770,771
                                                                        'catcher_id',#--------------------------------->> problem in catcher_id as in the workbench it is in but now in int as forcely changed
                                                                        # 'jobma_applied_date',#
                                                                        # 'jobma_contacted_date',#
                                                                        # 'jobma_contacted_text',#
                                                                        'status',#0,1,2,3,4---------->
                                                                        # 'tags',#test,arp,good,php,java
                                                                        # 'jobma_assessment_id',#float values  118.0,147.0,148.8.... mostly 0
                                                                        'invitation_id',#ids, mostly 0
                                                                        # 'documents',#mostly null or stringresums, summary
                                                                        #'status_name',#Null
                                                                        # 'pre_recorded_payment_status',#0,1 mostly 0
                                                                        # 'live_interview_payment_status',#0,1 mostly 0
                                                                        'apply_mode',#0,1,2,3,4,5,6 mostly
                                                                        'jobma_interview_rounds',#0,1,2,3,4
                                                                        # 'avg_ai_score',#Score generated by the AI found in only 15 tables
                                                                        # 'pre_screen_qualify',#0,1,2
                                                                        # 'integration_source',#one value in one colum
                                                                        # 'source',#jobma,microsoft teams,ZOom mostly jobma
                                                                        # 'export',#0,1 almost all are 0
                                                                        # 'deleted_rounds',####Problem  may be ticket raise
                                                                        # 'deleted_at',#
                                                                        # 'created_at',#
                                                                        # 'updated_at'
                                                                       ]].copy()

In [ ]:
jobma_pitcher_applied_jobs_selected_df.info()

In [ ]:
jobma_pitcher_applied_jobs_selected_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df.nunique()

In [ ]:
jobma_pitcher_applied_jobs_selected_df.duplicated().sum()

In [ ]:
jobma_pitcher_applied_jobs_selected_df['pitchers_counts'] = jobma_pitcher_applied_jobs_selected_df['catcher_id'].map(jobma_pitcher_applied_jobs_selected_df['catcher_id'].value_counts())

In [ ]:
jobma_pitcher_applied_jobs_selected_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df.nunique()

In [ ]:
jobma_pitcher_applied_jobs_selected_df.isna().sum()

In [ ]:
jobma_pitcher_applied_jobs_selected_df=jobma_pitcher_applied_jobs_selected_df[['catcher_id','pitchers_counts', 'apply_mode']]

In [ ]:
jobma_pitcher_applied_jobs_selected_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df.duplicated().sum()

In [ ]:
jobma_pitcher_applied_jobs_selected_df.drop_duplicates(inplace=True)

In [ ]:
jobma_pitcher_applied_jobs_selected_df.shape

In [ ]:
jobma_pitcher_applied_jobs_selected_df.isna().sum()

In [ ]:
jobma_pitcher_applied_jobs_selected_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df.to_csv("pitchers_df.csv", index=False)