In [1]:
#working on preprocessing

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

jobma_catcher_df = pd.read_sql("SELECT * FROM jobma_catcher", engine)

jobma_login_df = pd.read_sql("SELECT * FROM jobma_login", engine) #Usage details-------------How many times he logins__we willl take only value _counts 
jobma_wallet_df = pd.read_sql("SELECT * FROM wallet", engine) #How aggresively using + how much #account Wallet info
jobma_subscription_history_df = pd.read_sql("SELECT * FROM subscription_history", engine) #how much frequently using #subscription history


# kits created and used by client 
default_assessment_kits_df = pd.read_sql("SELECT * FROM default_assessment_kits", engine) #Not using right now
job_assessment_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine)
ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine)

#Featured kits data
kits_df=pd.read_csv('kits_pre_ai_outer_df.csv')

In [4]:
jobma_catcher_df.columns

Index(['jobma_catcher_id', 'jobma_catcher_fname', 'jobma_catcher_lname',
       'jobma_catcher_dob', 'jobma_catcher_video_status',
       'jobma_catcher_company', 'org_type', 'sec_ques_id', 'security_ans',
       'jobma_about_company', 'jobma_functional', 'jobma_catcher_indus',
       'jobma_company_email', 'jobma_catcher_email', 'jobma_catcher_title',
       'jobma_catcher_ext', 'jobma_catcher_otype', 'jobma_catcher_photo',
       'jobma_catcher_logo', 'jobma_catcher_website', 'jobma_company_address',
       'jobma_catcher_address2', 'jobma_catcher_video', 'jobma_catcher_city',
       'jobma_catcher_state', 'jobma_catcher_country', 'jobma_catcher_zip',
       'jobma_catcher_fax', 'jobma_catcher_phone', 'jobma_catcher_status',
       'jobma_catcher_creation', 'jobma_catcher_type',
       'jobma_catcher_sub_accounts', 'is_premium', 'jobma_catcher_parent',
       'jobma_catcher_is_deleted', 'jobma_verified', 'jobma_in_index',
       'data_access', 'subscription_status', 'interview_rate',
       'remember_token', 'deleted_at', 'api_key', 'sub_user', 'per_sub_user',
       'live_interview_credit', 'pre_recorded_credit',
       'ai_live_interview_credit', 'credit_value', 'interview_cost_type',
       'subscription_type', 'phone_call_cost_type',
       'call_and_regording_credits', 'transcription_credits',
       'temp_subscription_type', 'created_at', 'updated_at',
       'jobma_support_rtc', 'interview_question', 'video_recording_suppport',
       'subaccount_permission', 'reply_email', 'sing_up_canditate_after_apply',
       'currency', 'referral_credit', 'company_size', 'theme', 'flag',
       'jobma_auto_recording_status', 'jobma_scenario_question_status',
       'ai_live_interview', 'ms_teams_chat_reference', 'bot_audio',
       'approval'],
      dtype='object')

In [5]:
jobma_catcher_selected_df= jobma_catcher_df[['jobma_catcher_id',
                                             'jobma_catcher_company',#@1890       #About compny[ssi, jobma, golden compass, uk aviation]
                                             'sec_ques_id',         #@4    #values are 0,1,2,3----->0..................................???
                                             'jobma_functional',      #IT, HR, Airlines, Supply, accounting, sales--------------------->??
                                             'jobma_catcher_indus',   #342  #mostly id, software, it, 
                                             'jobma_catcher_title', #@9     #0,1,2......8----------------------------------------------???
                                             'jobma_catcher_ext',   #123,357,789,1234.................................................>>??
                                             'jobma_catcher_otype',    #1,2,Employer,recruiting firm,ad agency, 101,18
                                             'jobma_catcher_status',   #0,1
                                             'jobma_catcher_creation',#date-------------------------------------##required for age of usage
                                             'jobma_catcher_type',    #0,1
                                             'jobma_catcher_sub_accounts',#0,_,7,49
                                             'is_premium',#0,1
                                             'jobma_catcher_parent',#0.92,1873,1692
                                             'jobma_catcher_is_deleted',#0,1------------------------------------#required for age of usage
                                             'jobma_verified',#0,1 Mostly 
                                             'jobma_in_index',#mostly 1,     
                                             'data_access',#mostly 1,     
                                             'subscription_status',#1,2,3    
                                             'sub_user',#0,1,2,10,999
                                             'per_sub_user',#10,10000,60,[60,100]
                                             'live_interview_credit',#0.0,1.0,1.5,15
                                             'pre_recorded_credit',#0.0,1.0,1.5,2.0,15
                                             'ai_live_interview_credit',#1.0,2.0  mostly 1
                                             'credit_value',#1,2,4,5,8 mostly 1
                                             'interview_cost_type',#0,1
                                             'subscription_type',#0,1
                                             'created_at',#creation date----------------------------------------------------------->To find Age at jobma
                                             'subaccount_permission',#
                                             'referral_credit',#0,100,200,400 mostky 0------------->>>
                                             'company_size',#1-25, 26-100, 101-500, 500-1000, morethan 1000-----------------------         #########used
                                             'ai_live_interview',#0,1---0
                                             'approval',#only 0
                                            ]]

In [6]:
jobma_catcher_selected_df.to_csv("catcher_df.csv", index=False)

In [7]:
jobma_wallet_selected_df = jobma_wallet_df[['catcher_id', 
                                            'credit_amount',
                                            'wallet_amount', 
                                            'subscription_type', 
                                            'plan_type',
                                            'is_unlimited',
                                            'trial_account_type',
                                            'billing_cycle_status'
                                         ]].copy()

In [8]:
jobma_subscription_history_selected_df = jobma_subscription_history_df[['catcher_id', 
                                                                        'premium_plan',  
                                                                        'subscription_amount',  
                                                                        'credit_given',  
                                                                        'expiry_date',
                                                                        'currency',  
                                                                        'currency_val',  
                                                                        'payment_mode',
                                                                        'status',  
                                                                        'payment_status',
                                                                        'e_invoice'
                                                                       ]].copy()

In [9]:
jobma_catcher_selected_df = jobma_catcher_selected_df.rename(columns={'jobma_catcher_id': 'catcher_id'})

In [10]:
jobma_catcher_selected_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7672 entries, 0 to 7671
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   catcher_id                  7672 non-null   int64
 1   jobma_catcher_company       7672 non-null   object
 2   sec_ques_id                 7672 non-null   int64
 3   jobma_functional            7672 non-null   object
 4   jobma_catcher_indus         6126 non-null   object
 5   jobma_catcher_title         7672 non-null   int64
 6   jobma_catcher_ext           7672 non-null   object
 7   jobma_catcher_otype         7672 non-null   object
 8   jobma_catcher_status        7649 non-null   object
 9   jobma_catcher_creation      7672 non-null   object
 10  jobma_catcher_type          5425 non-null   object
 11  jobma_catcher_sub_accounts  7672 non-null   object
 12  is_premium                  7672 non-null   object
 13  jobma_catcher_parent        7672 non-null   int64
 14  jobma_catcher_is_deleted    257 non-null    object
 15  jobma_verified              7672 non-null   object
 16  jobma_in_index              7354 non-null   object
 17  data_access                 7672 non-null   object
 18  subscription_status         7672 non-null   object
 19  sub_user                    7672 non-null   int64
 20  per_sub_user                7672 non-null   object
 21  live_interview_credit       7672 non-null   float64
 22  pre_recorded_credit         7672 non-null   float64
 23  ai_live_interview_credit    7672 non-null   float64
 24  credit_value                7672 non-null   int64
 25  interview_cost_type         7672 non-null   object
 26  subscription_type           7672 non-null   object
 27  created_at                  7672 non-null   datetime64[ns]
 28  subaccount_permission       7670 non-null   object
 29  referral_credit             7672 non-null   int64
 30  company_size                5934 non-null   object
 31  ai_live_interview           7672 non-null   object
 32  approval                    7672 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(7), object(22)
memory usage: 1.9+ MB

In [11]:
jobma_catcher_selected_df.isna().sum().sort_values(ascending=False)

jobma_catcher_is_deleted      7415
jobma_catcher_type            2247
company_size                  1738
jobma_catcher_indus           1546
jobma_in_index                 318
jobma_catcher_status            23
subaccount_permission            2
catcher_id                       0
jobma_functional                 0
jobma_catcher_otype              0
jobma_catcher_ext                0
jobma_catcher_title              0
jobma_catcher_creation           0
is_premium                       0
jobma_catcher_sub_accounts       0
sec_ques_id                      0
jobma_catcher_company            0
jobma_verified                   0
jobma_catcher_parent             0
data_access                      0
subscription_status              0
live_interview_credit            0
pre_recorded_credit              0
sub_user                         0
per_sub_user                     0
credit_value                     0
ai_live_interview_credit         0
subscription_type                0
interview_cost_type              0
created_at                       0
referral_credit                  0
ai_live_interview                0
approval                         0
dtype: int64

In [12]:
jobma_wallet_selected_df

,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,trial_account_type,billing_cycle_status
0,669,NaN,0.0,0,0,0,NaN,0
1,92,NaN,34.0,0,0,0,0.0,0
2,898,NaN,0.0,0,0,0,NaN,0
3,912,NaN,0.0,0,0,0,NaN,0
4,92,NaN,3.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...
5557,9319,NaN,500000.0,0,0,1,0.0,1
5558,9365,NaN,137.0,0,0,0,0.0,0
5559,9405,NaN,500000.0,0,0,1,0.0,0
5560,9413,NaN,15000.0,0,0,0,0.0,0
5561,9445,NaN,150.0,0,0,0,0.0,0

In [13]:
jobma_wallet_selected_df.nunique()

catcher_id              5560
credit_amount             39
wallet_amount            715
subscription_type          2
plan_type                  3
is_unlimited               3
trial_account_type         2
billing_cycle_status       2
dtype: int64

In [14]:
#Joining wallet and subscription history
wallet_sub_inner_df = pd.merge(jobma_wallet_selected_df, jobma_subscription_history_selected_df, on='catcher_id', how='inner')
wallet_sub_inner_df.shape

(11047, 18)

In [15]:
wallet_sub_inner_df

,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,trial_account_type,billing_cycle_status,premium_plan,subscription_amount,credit_given,expiry_date,currency,currency_val,payment_mode,status,payment_status,e_invoice
0,92,NaN,34.0,0,0,0,0.0,0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0,0
1,92,NaN,34.0,0,0,0,0.0,0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1,1
2,898,NaN,0.0,0,0,0,NaN,0,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0,0
3,92,NaN,3.0,0,0,0,0.0,0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0,0
4,92,NaN,3.0,0,0,0,0.0,0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11042,9319,NaN,500000.0,0,0,1,0.0,1,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2025-06-18,1,1.0,3,1,1,0
11043,9365,NaN,137.0,0,0,0,0.0,0,"{""subscription_charges"": ""50"", ""email_support""...",50.0,50,2025-07-11,0,1.0,1,1,1,0
11044,9405,NaN,500000.0,0,0,1,0.0,0,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2044-12-31,1,1.0,3,1,1,0
11045,9413,NaN,15000.0,0,0,0,0.0,0,"{""subscription_charges"":""150"",""email_support"":...",150.0,150,2025-09-24,0,1.0,1,1,1,0
11046,9445,NaN,150.0,0,0,0,0.0,0,"{""subscription_charges"":""150"",""email_support"":...",0.0,150,2035-03-31,0,0.0,3,1,1,0

In [16]:
jobma_catcher_selected_df.shape, jobma_wallet_selected_df.shape, jobma_subscription_history_selected_df.shape

((7672, 33), (5562, 8), (11049, 11))

In [17]:
# wallet_sub_inner_df.corr(numeric_only=True)

In [18]:
# plt.figure(figsize=(10, 8))
# corr_matrix = wallet_sub_inner_df.corr(numeric_only=True)
# sns.heatmap(corr_matrix, annot=True,fmt='.2f', cmap='coolwarm',  linewidths=0.5, linecolor='gray', square=True, cbar_kws={"shrink": 0.75}, annot_kws={"size": 10})
# plt.show()

In [19]:
#Joining catcher, wallet and subscription history
catcher_wallet_sub_inner_df = pd.merge(jobma_catcher_selected_df, jobma_subscription_history_selected_df, on='catcher_id', how='inner')
catcher_wallet_sub_inner_df.shape

(11005, 43)

In [20]:
catcher_wallet_sub_inner_df

,catcher_id,jobma_catcher_company,sec_ques_id,jobma_functional,jobma_catcher_indus,jobma_catcher_title,jobma_catcher_ext,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_creation,...,premium_plan,subscription_amount,credit_given,expiry_date,currency,currency_val,payment_mode,status,payment_status,e_invoice
0,92,Select Source International,1,,,0,,1,1,2016-11-22,...,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0,0
1,92,Select Source International,1,,,0,,1,1,2016-11-22,...,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1,1
2,106,Singhal System Solutions Pvt. Ltd.,0,IT Software- ERP / CRM,IT-Software/Software Services,0,,,-1,2012-12-08,...,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0,0
3,124,Aviation Company,0,Airlines & Automotive,Airline,0,,,1,2013-11-15,...,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0,0
4,125,Uk Aviation Company,0,Airlines & Automotive,Airline,0,,,1,2013-11-18,...,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11000,9319,IND,0,,72,4,,1,1,0000-00-00,...,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2025-06-18,1,1.0,3,1,1,0
11001,9365,SSI,0,,1,0,,,1,0000-00-00,...,"{""subscription_charges"": ""50"", ""email_support""...",50.0,50,2025-07-11,0,1.0,1,1,1,0
11002,9405,Jobma Share Holder,0,,85,1,,1,1,0000-00-00,...,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2044-12-31,1,1.0,3,1,1,0
11003,9413,Company name,0,,1,0,,,1,0000-00-00,...,"{""subscription_charges"":""150"",""email_support"":...",150.0,150,2025-09-24,0,1.0,1,1,1,0
11004,9445,Jobma,0,,74,1,,,1,0000-00-00,...,"{""subscription_charges"":""150"",""email_support"":...",0.0,150,2035-03-31,0,0.0,3,1,1,0

# job_assessment_kit + #ai_video_kit

In [21]:
job_assessment_kit_df.nunique()

id                 5852
catcher_id         1082
title              3581
slug               5734
answer_duration      46
interview_type        5
question_set       5019
pre_screening        55
ques_ids           4855
weightage             2
weightage_data        2
description          17
price                 5
currency              1
expiry               12
status                2
is_active             2
offer_status          3
sr_id                 8
main_sr_id            2
node_id               1
random_ques           3
random_options        3
is_streaming          2
deleted_at            0
created_at         5190
updated_at          702
dtype: int64

In [22]:
# catcher_wallet_sub_inner_df.isna().sum().sort_values(ascending=False)

In [23]:
#job_assessment_kit - Kits created by employers for Pre-recorded interview
job_assessment_kit_df['pre_recorded_kits_count'] = job_assessment_kit_df['catcher_id'].map(job_assessment_kit_df['catcher_id'].value_counts())
job_assessment_kit_df=job_assessment_kit_df[['catcher_id','pre_recorded_kits_count']]

In [24]:
job_assessment_kit_df['catcher_id'].nunique()

1082

In [25]:
job_assessment_kit_df.head(20)

    catcher_id  pre_recorded_kits_count
0          908                       44
1         1209                       69
2         1209                       69
3         1209                       69
4         1209                       69
5         1235                        9
6         1040                        4
7         1040                        4
8         1209                       69
9         1209                       69
10        1268                        2
11        1268                        2
12        1209                       69
13        1209                       69
14        1235                        9
15        1235                        9
16        1235                        9
17         908                       44
18        1235                        9
19        1269                        4

In [26]:
job_assessment_kit_df = job_assessment_kit_df.drop_duplicates()

In [27]:
job_assessment_kit_df

      catcher_id  pre_recorded_kits_count
0            908                       44
1           1209                       69
5           1235                        9
6           1040                        4
10          1268                        2
...          ...                      ...
5786        9299                        1
5794        9313                        1
5812        6543                        5
5828        9433                        1
5849        9443                        1

[1082 rows x 2 columns]

In [28]:
#ai_video_kit - Kits created by employers for AI Live interview
ai_video_kit_df['ai_live_kits_count'] = ai_video_kit_df['catcher_id'].map(ai_video_kit_df['catcher_id'].value_counts())

In [29]:
ai_video_kit_df=ai_video_kit_df[['catcher_id','ai_live_kits_count']]
ai_video_kit_df.shape

(52, 2)

In [30]:
ai_video_kit_df.nunique()

catcher_id            9
ai_live_kits_count    4
dtype: int64

In [31]:
ai_video_kit_df = ai_video_kit_df.drop_duplicates()

In [32]:
ai_video_kit_df.shape

(9, 2)

In [33]:
ai_video_kit_df

    catcher_id  ai_live_kits_count
0         1873                  32
16        8873                  10
27        9265                   1
29        8597                   1
40        6543                   1
43        8565                   4
48        9299                   1
49        9313                   1
51        9443                   1

In [34]:
kits_df

      catcher_id  kits_count
0              0          17
1              1          96
2             92           2
3            151           1
4            207           1
...          ...         ...
1078        9413           1
1079        9415           1
1080        9433           1
1081        9443           1
1082        9579           1

[1083 rows x 2 columns]