In [1]:
#working on kits to combine them and use them

In [2]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
#kits created and used by client 
default_assessment_kits_df = pd.read_sql("SELECT * FROM default_assessment_kits", engine) 
job_assessment_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine)
ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine)

In [4]:
default_assessment_kits_df.columns

Index(['id', 'kit_name', 'interview_type', 'interview_category', 'category_id',
       'sub_category_id', 'kit_description', 'question_set', 'ques_ids',
       'industry_id', 'status', 'created_at', 'updated_at'],
      dtype='object')

In [5]:
job_assessment_kit_df.columns

Index(['id', 'catcher_id', 'title', 'slug', 'answer_duration',
       'interview_type', 'question_set', 'pre_screening', 'ques_ids',
       'weightage', 'weightage_data', 'description', 'price', 'currency',
       'expiry', 'status', 'is_active', 'offer_status', 'sr_id', 'main_sr_id',
       'node_id', 'random_ques', 'random_options', 'is_streaming',
       'deleted_at', 'created_at', 'updated_at'],
      dtype='object')

In [6]:
ai_video_kit_df.columns

Index(['id', 'catcher_id', 'title', 'slug', 'answer_duration', 'question_set',
       'min_experience', 'max_experience', 'interview_level',
       'evaluation_keywords', 'is_active', 'deleted_at', 'created_at',
       'updated_at'],
      dtype='object')

In [7]:
default_assessment_kits_df.head(5)

,id,kit_name,interview_type,interview_category,category_id,sub_category_id,kit_description,question_set,ques_ids,industry_id,status,created_at,updated_at
0,361,Common questions,0,0,1,NaN,Designed to assess professional background and...,"{""question"": [{""ques"": ""intro"", ""media"": [], ""...","1_30854,1_30855,1_30856,1_30857,1_30858",43,1,2023-05-26 10:55:24,2024-10-14 06:25:47
1,362,Web Developer,0,0,15,NaN,"Focused on technical proficiency, this kit eva...","{""question"": [{""ques"": ""intro"", ""media"": [], ""...","1_30859,1_30860,1_30861,1_30862,1_30863",43,1,2023-05-26 10:55:24,2024-10-14 06:25:47
2,363,Senior Sales Administrator,0,0,1,NaN,Designed to assess sales administration expert...,"{""question"": [{""ques"": ""intro"", ""media"": [], ""...","1_30864,1_30865,1_30866,1_30867,1_30868",43,1,2023-05-26 10:55:24,2024-10-14 06:25:47
3,364,Senior Associate - Customer Support,0,0,1,NaN,The Customer Support Kit evaluates a candidate...,"{""question"": [{""ques"": ""intro"", ""media"": [], ""...","1_30869,1_30870,1_30871,1_30872,1_30873",43,1,2023-05-26 10:55:24,2024-10-14 06:25:47
4,365,Web Designer,0,0,15,NaN,A candidate's skills in web development are as...,"{""question"": [{""ques"": ""intro"", ""media"": [], ""...","1_30874,1_30875,1_30876,1_30877,1_30878",43,1,2023-05-26 10:55:24,2024-10-14 06:25:47

In [8]:
ai_video_kit_df.head(5)

,id,catcher_id,title,slug,answer_duration,question_set,min_experience,max_experience,interview_level,evaluation_keywords,is_active,deleted_at,created_at,updated_at
0,13,1873,Jquery,jquery,300,"[{""id"":""1"",""ques"":""Added question""},{""id"":""2"",...",0,2,2,"[""Python"", ""Jquery"", ""Laravel""]",1,None,2024-10-15 05:22:46,2024-10-15 05:22:46
1,14,1873,React,react-4,1800,"[{""id"":""1"",""ques"":""Can you explain what React ...",1,3,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:23:49,2024-10-15 05:23:49
2,15,1873,Kit,kit,300,"[{""id"":""1"",""ques"":""Can you explain what React ...",2,6,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:31:13,2024-10-15 05:31:13
3,16,1873,Python,python,1200,"[{""id"":""1"",""ques"":""Can you explain the differe...",29,50,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:33:12,2024-10-15 05:33:12
4,17,1873,Javascript,javascript,300,"[{""id"":""1"",""ques"":""Can you explain the differe...",1,3,2,"[""Coding Skills""]",1,None,2024-10-15 05:44:30,2024-10-15 05:44:30

In [9]:
ai_video_kit_df.head(5)

,id,catcher_id,title,slug,answer_duration,question_set,min_experience,max_experience,interview_level,evaluation_keywords,is_active,deleted_at,created_at,updated_at
0,13,1873,Jquery,jquery,300,"[{""id"":""1"",""ques"":""Added question""},{""id"":""2"",...",0,2,2,"[""Python"", ""Jquery"", ""Laravel""]",1,None,2024-10-15 05:22:46,2024-10-15 05:22:46
1,14,1873,React,react-4,1800,"[{""id"":""1"",""ques"":""Can you explain what React ...",1,3,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:23:49,2024-10-15 05:23:49
2,15,1873,Kit,kit,300,"[{""id"":""1"",""ques"":""Can you explain what React ...",2,6,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:31:13,2024-10-15 05:31:13
3,16,1873,Python,python,1200,"[{""id"":""1"",""ques"":""Can you explain the differe...",29,50,2,"[""Js"", ""Ruby"", ""React""]",1,None,2024-10-15 05:33:12,2024-10-15 05:33:12
4,17,1873,Javascript,javascript,300,"[{""id"":""1"",""ques"":""Can you explain the differe...",1,3,2,"[""Coding Skills""]",1,None,2024-10-15 05:44:30,2024-10-15 05:44:30

In [10]:
job_assessment_kit_df.shape, ai_video_kit_df.shape

((5852, 27), (52, 14))

In [11]:
kits_pre_ai_outer_df = pd.merge(job_assessment_kit_df, ai_video_kit_df,
                           on='catcher_id',
                           how='outer')

In [12]:
kits_pre_ai_outer_df.nunique()

id_x                   5852
catcher_id             1083
title_x                3581
slug_x                 5734
answer_duration_x        46
interview_type            5
question_set_x         5019
pre_screening            55
ques_ids               4855
weightage                 2
weightage_data            2
description              17
price                     5
currency                  1
expiry                   12
status                    2
is_active_x               2
offer_status              3
sr_id                     8
main_sr_id                2
node_id                   1
random_ques               3
random_options            3
is_streaming              2
deleted_at_x              0
created_at_x           5190
updated_at_x            702
id_y                     52
title_y                  38
slug_y                   48
answer_duration_y         8
question_set_y           40
min_experience            9
max_experience           11
interview_level           3
evaluation_keywords      37
is_active_y               2
deleted_at_y              0
created_at_y             51
updated_at_y             52
dtype: int64

In [13]:
kits_pre_ai_outer_df.shape

(15261, 40)

In [14]:
kits_pre_ai_outer_df.isna().sum().sort_values(ascending=False)

deleted_at_x           15261
deleted_at_y           15261
node_id                15260
offer_status           15232
sr_id                  15232
weightage_data         15197
expiry                 14572
description            14545
pre_screening          14343
answer_duration_x      10247
created_at_y            5410
updated_at_y            5410
id_y                    5410
slug_y                  5410
interview_level         5410
max_experience          5410
title_y                 5410
min_experience          5410
question_set_y          5410
answer_duration_y       5410
is_active_y             5410
evaluation_keywords     5410
title_x                    1
id_x                       1
weightage                  1
question_set_x             1
slug_x                     1
interview_type             1
is_streaming               1
random_options             1
currency                   1
status                     1
is_active_x                1
ques_ids                   1
random_ques                1
main_sr_id                 1
created_at_x               1
price                      1
updated_at_x               1
catcher_id                 0
dtype: int64

In [16]:
#job_assessment_kit - 
#Kits created by employers for Pre-recorded interview


kits_pre_ai_outer_df['kits_count'] = kits_pre_ai_outer_df['catcher_id'].map(kits_pre_ai_outer_df['catcher_id'].value_counts())
kits_pre_ai_outer_df=kits_pre_ai_outer_df[['catcher_id','kits_count']]

In [17]:
kits_pre_ai_outer_df.shape

(15261, 2)

In [18]:
kits_pre_ai_outer_df.nunique()

catcher_id    1083
kits_count      61
dtype: int64

In [19]:
kits_pre_ai_outer_df.value_counts().head(50)

catcher_id  kits_count
1873        9504          9504
5943        196            196
8565        184            184
2335        172            172
5947        151            151
1839        151            151
723         145            145
2169        131            131
5814        124            124
1371        106            106
6475        97              97
1           96              96
6139        96              96
7464        90              90
1692        85              85
8597        84              84
6184        82              82
5874        80              80
5898        75              75
5335        71              71
8873        70              70
1209        69              69
6111        67              67
1412        61              61
289         59              59
712         57              57
7151        55              55
2334        50              50
716         48              48
908         44              44
6968        42              42
5868        41              41
8464        41              41
1730        37              37
6414        36              36
1372        36              36
1347        35              35
2266        35              35
6411        35              35
2046        34              34
6185        31              31
5800        31              31
9035        30              30
7596        29              29
2155        29              29
5818        29              29
3678        27              27
8067        25              25
8305        25              25
446         24              24
Name: count, dtype: int64

In [20]:
# assess_ai_inner_df.duplicates().sum()
kits_pre_ai_outer_df.duplicated().sum()

np.int64(14178)

In [29]:
kits_pre_ai_outer_df = kits_pre_ai_outer_df.drop_duplicates()

In [30]:
kits_pre_ai_outer_df.nunique()

catcher_id    1083
kits_count      61
dtype: int64

In [31]:
kits_pre_ai_outer_df

       catcher_id  kits_count
0               0          17
17              1          96
113            92           2
115           151           1
116           207           1
...           ...         ...
15256        9413           1
15257        9415           1
15258        9433           1
15259        9443           1
15260        9579           1

[1083 rows x 2 columns]

In [32]:
kits_pre_ai_outer_df.to_csv('kits_pre_ai_outer_df.csv', index=False)